import type { DishTemplate } from "@/lib/types";
import { c, k, p } from "./helpers";

export const DISHES_AFRICA_AMERICAS: DishTemplate[] = [
  {
    id: "jollof-rice",
    name: "Jollof Rice",
    aliases: ["jollof", "jollof rice", "nigerian jollof", "party jollof", "ghana jollof", "ghanaian jollof"],
    cuisine: "Nigerian",
    country: "Nigeria",
    region: "West Africa",
    flag: "🇳🇬",
    image: "/images/jollof.jpg",
    description: "Smoky, tomato-rich West African party rice — the dish that starts friendly wars between Lagos and Accra.",
    servings: 6, prep: 20, cook: 60, difficulty: "Medium",
    ingredients: [
      c("Long-grain parboiled rice", "3 cups", "Rice & Grains", 3.49),
      c("Roma tomatoes", "6", "Produce", 2.99),
      c("Red bell peppers", "2", "Produce", 2.98),
      c("Yellow onions", "2", "Produce", 1.49),
      k("scotch-bonnet", "2"),
      c("Tomato paste", "3 tbsp", "Canned Goods", 1.29),
      c("Chicken stock", "3 cups", "Soups & Broths", 2.99),
      k("maggi", "2 cubes"),
      k("nigerian-curry", "1½ tsp"),
      c("Dried thyme", "1 tsp", "Spices", 2.99),
      c("Bay leaves", "3", "Spices", 2.99),
      c("Unsalted butter", "2 tbsp", "Dairy", 4.49),
      p("Vegetable oil", "⅓ cup"),
      p("Salt", "to taste"),
    ],
    steps: [
      "Blend the tomatoes, red bell peppers, 1 onion and {scotch-bonnet} until smooth. Simmer the purée for 10–15 minutes until reduced by about a third.",
      "Wash the rice in several changes of water until it runs clear, then drain well.",
      "Heat the oil in a heavy pot and fry the second onion (sliced) until soft. Stir in the tomato paste and fry 3–4 minutes until it darkens to a deep brick red.",
      "Add the reduced pepper purée, {nigerian-curry}, dried thyme, bay leaves and crumbled {maggi}. Fry, stirring, until the oil floats to the top — about 10 minutes.",
      "Stir in the rice and stock, season with salt, then cover tightly with foil and the lid. Cook on low heat for 25–30 minutes without stirring.",
      "When the rice is tender, raise the heat for 2–3 minutes to build the smoky 'party' bottom, then fold in the butter and serve with fried plantains.",
    ],
    tips: [
      "Party jollof gets its smoky flavor from slightly scorching the bottom — don't skip that last high-heat minute.",
      "Parboiled rice (like Ben's Original) absorbs the stew without turning mushy.",
    ],
  },
  {
    id: "egusi-soup",
    name: "Egusi Soup",
    aliases: ["egusi", "egusi soup", "efo egusi", "melon seed soup"],
    cuisine: "Nigerian",
    country: "Nigeria",
    region: "West Africa",
    flag: "🇳🇬",
    image: null,
    description: "A hearty Nigerian soup of ground melon seeds, leafy greens and palm oil, made for scooping with pounded yam.",
    servings: 6, prep: 30, cook: 60, difficulty: "Medium",
    ingredients: [
      k("egusi", "1½ cups"),
      k("palm-oil", "½ cup"),
      c("Beef chuck or goat meat", "2 lb", "Meat & Seafood", 14.99),
      k("stockfish", "½ lb"),
      k("ground-crayfish", "3 tbsp"),
      k("iru", "1 tbsp"),
      k("ugu", "4 cups chopped"),
      k("scotch-bonnet", "2"),
      c("Yellow onion", "1 large", "Produce", 0.99),
      k("maggi", "2 cubes"),
      k("pounded-yam", "for serving"),
      p("Water", "4 cups"),
      p("Salt", "to taste"),
    ],
    steps: [
      "Season the meat with half the chopped onion, one of the {maggi} and salt. Simmer with the {stockfish} in 4 cups of water until tender, about 40 minutes. Reserve the stock.",
      "Mix the {egusi} with a few tablespoons of water into a thick paste.",
      "Warm the {palm-oil} in a large pot over medium heat (don't let it smoke). Fry the remaining onion, then spoon in the egusi paste in clumps and fry 5–7 minutes, turning, until it curdles and turns golden.",
      "Gradually pour in the meat stock, then add the meat, {ground-crayfish}, {iru}, blended {scotch-bonnet} and the remaining {maggi}. Simmer 15 minutes, stirring occasionally.",
      "Stir in the {ugu} and cook 3–5 minutes until just wilted. Adjust the salt.",
      "Serve hot with {pounded-yam}, eba or rice.",
    ],
    tips: [
      "Fry the egusi in clumps without over-stirring — the curds are the best part.",
      "Egusi freezes beautifully and tastes even better reheated.",
    ],
  },
  {
    id: "doro-wat",
    name: "Doro Wat",
    aliases: ["doro wat", "doro wot", "doro wet", "ethiopian chicken stew"],
    cuisine: "Ethiopian",
    country: "Ethiopia",
    region: "East Africa",
    flag: "🇪🇹",
    image: null,
    description: "Ethiopia's celebratory chicken stew — slow-cooked onions, fiery berbere and spiced butter, served on injera.",
    servings: 6, prep: 30, cook: 90, difficulty: "Weekend project",
    ingredients: [
      c("Bone-in chicken drumsticks & thighs", "3 lb", "Meat & Seafood", 9.99),
      c("Red onions", "4 large", "Produce", 3.96),
      k("niter-kibbeh", "½ cup"),
      k("berbere", "¼ cup"),
      c("Garlic", "6 cloves", "Produce", 0.69),
      c("Fresh ginger", "2-inch piece", "Produce", 1.29),
      c("Tomato paste", "2 tbsp", "Canned Goods", 1.29),
      c("Eggs", "6", "Dairy", 3.49),
      c("Lemon", "1", "Produce", 0.79),
      k("teff", "for injera"),
      p("Water", "2 cups"),
      p("Salt", "to taste"),
    ],
    steps: [
      "Toss the chicken with lemon juice and salt and set aside for 20 minutes. Hard-boil the eggs, peel, and score them lightly.",
      "Finely chop or pulse the red onions. Cook them in a dry pot over medium-low heat for 20–30 minutes, stirring, until deeply soft and jammy — no fat yet.",
      "Add the {niter-kibbeh} and cook 5 minutes, then stir in {berbere}, the garlic, ginger and tomato paste. Cook until fragrant and brick-red, about 5 minutes.",
      "Add the chicken and 2 cups of water. Simmer, partly covered, for 45 minutes until the sauce is thick and the chicken is tender.",
      "Nestle in the eggs and simmer 10 minutes more. Serve on injera made from {teff}.",
    ],
    tips: [
      "Slow-cooked onions are the soul of wat — don't rush them.",
      "Doro wat tastes even better on day two.",
    ],
  },
  {
    id: "jerk-chicken",
    name: "Jerk Chicken",
    aliases: ["jerk chicken", "jerk", "jamaican jerk", "jamaican jerk chicken"],
    cuisine: "Jamaican",
    country: "Jamaica",
    region: "Caribbean",
    flag: "🇯🇲",
    image: "/images/jerk.jpg",
    description: "Fiery, smoky Jamaican chicken marinated in scotch bonnets, allspice and thyme, then cooked over pimento wood.",
    servings: 6, prep: 20, cook: 45, difficulty: "Medium",
    ingredients: [
      c("Chicken leg quarters", "4 lb", "Meat & Seafood", 7.99),
      k("scotch-bonnet", "4"),
      c("Scallions", "1 bunch", "Produce", 0.99),
      c("Fresh thyme", "1 small bunch", "Produce", 2.49),
      c("Ground allspice", "1 tbsp", "Spices", 3.49),
      c("Garlic", "6 cloves", "Produce", 0.69),
      c("Fresh ginger", "1-inch piece", "Produce", 1.29),
      c("Limes", "2", "Produce", 1.99),
      c("Soy sauce", "¼ cup", "International", 2.99),
      c("Brown sugar", "2 tbsp", "Baking", 2.49),
      k("browning", "1 tbsp"),
      k("pimento-wood", "for the grill"),
      c("Ground cinnamon & nutmeg", "½ tsp each", "Spices", 2.99),
      p("Vegetable oil", "2 tbsp"),
      p("Salt & black pepper", "to taste"),
    ],
    steps: [
      "Blend the {scotch-bonnet}, scallions, thyme leaves, allspice, garlic, ginger, lime juice, soy sauce, brown sugar, {browning}, cinnamon, nutmeg, oil, salt and pepper into a thick marinade.",
      "Slash the chicken to the bone, rub the marinade deep into the cuts (wear gloves!) and refrigerate at least 4 hours — overnight is best.",
      "Set up the grill for two-zone heat. For the signature smoke, add {pimento-wood} to the coals or a smoker box.",
      "Grill the chicken over indirect heat, covered, for 35–40 minutes, turning occasionally, then move it over direct heat to char for 5 minutes.",
      "Rest 5 minutes, chop into pieces and serve with rice and peas and fried plantain.",
    ],
    tips: [
      "No grill? Roast at 400°F for 45 minutes, then broil to char.",
      "Set aside some marinade before it touches raw chicken — it makes a fiery dipping sauce.",
    ],
  },
  {
    id: "ropa-vieja",
    name: "Ropa Vieja",
    aliases: ["ropa vieja", "cuban shredded beef", "carne ripiada"],
    cuisine: "Cuban",
    country: "Cuba",
    region: "Caribbean",
    flag: "🇨🇺",
    image: null,
    description: "Cuba's national dish — tender shredded beef simmered in a sofrito of peppers, tomato and sour orange.",
    servings: 6, prep: 20, cook: 150, difficulty: "Easy",
    ingredients: [
      c("Flank steak", "2½ lb", "Meat & Seafood", 19.99),
      k("sour-orange", "½ cup"),
      k("sazon", "1 packet"),
      k("culantro", "4 leaves"),
      c("Green bell pepper", "1", "Produce", 0.99),
      c("Red bell pepper", "1", "Produce", 1.49),
      c("Yellow onion", "1 large", "Produce", 0.99),
      c("Garlic", "5 cloves", "Produce", 0.69),
      c("Tomato sauce", "1 (15-oz) can", "Canned Goods", 1.19),
      c("Dry white wine", "½ cup", "Wine & Cooking Wine", 6.99),
      c("Pimento-stuffed green olives", "½ cup", "Condiments", 3.49),
      c("Ground cumin", "1 tsp", "Spices", 2.99),
      c("Dried oregano", "1 tsp", "Spices", 2.49),
      c("Bay leaves", "2", "Spices", 2.99),
      p("Olive oil", "3 tbsp"),
      p("Salt & pepper", "to taste"),
    ],
    steps: [
      "Season the flank steak with salt, pepper and {sazon} (use half now, half later). Sear in olive oil in a Dutch oven until browned on both sides; remove.",
      "Sauté the sliced onion and bell peppers until soft, then add the garlic, cumin, oregano and the remaining seasoning.",
      "Deglaze with the white wine, then add the tomato sauce, {sour-orange}, bay leaves and {culantro}. Return the beef with its juices.",
      "Cover and simmer gently for 2–2½ hours (or 50 minutes in a pressure cooker) until the beef falls apart.",
      "Shred the beef with two forks right in the sauce, stir in the olives and simmer 10 minutes more. Serve with white rice, black beans and sweet plantains.",
    ],
    tips: [
      "Ropa vieja means 'old clothes' — the beef should shred into rag-like strands.",
      "Make it a day ahead; the flavors deepen overnight.",
    ],
  },
  {
    id: "mole-poblano",
    name: "Mole Poblano",
    aliases: ["mole", "mole poblano", "chicken mole", "mole de pollo", "pollo en mole"],
    cuisine: "Mexican",
    country: "Mexico",
    region: "Latin America",
    flag: "🇲🇽",
    image: "/images/mole.jpg",
    description: "Puebla's legendary sauce of three dried chiles, nuts, spices and chocolate, ladled over tender chicken.",
    servings: 8, prep: 45, cook: 120, difficulty: "Weekend project",
    ingredients: [
      k("chile-mulato", "4"),
      k("ancho", "4"),
      k("chile-pasilla", "3"),
      k("mexican-chocolate", "2 oz"),
      k("canela", "1 stick"),
      c("Whole chicken, cut into pieces", "4 lb", "Meat & Seafood", 9.99),
      c("Roma tomatoes", "2", "Produce", 0.99),
      c("Tomatillos", "3", "Produce", 1.49),
      c("White onion", "1", "Produce", 0.99),
      c("Garlic", "4 cloves", "Produce", 0.69),
      c("Sesame seeds", "¼ cup", "Spices", 3.49),
      c("Almonds", "¼ cup", "Snacks & Nuts", 4.99),
      c("Raisins", "¼ cup", "Snacks & Nuts", 2.99),
      c("Corn tortillas", "2 (stale)", "International", 2.49),
      c("Chicken broth", "4 cups", "Soups & Broths", 2.99),
      c("Whole cloves & black peppercorns", "4 each", "Spices", 4.29),
      c("Anise seed", "½ tsp", "Spices", 3.49),
      p("Lard or vegetable oil", "¼ cup"),
      p("Sugar & salt", "to taste"),
    ],
    steps: [
      "Poach the chicken in salted water with half the onion for 40 minutes; reserve 4 cups of the broth.",
      "Prepare the chiles — {chile-mulato}, {ancho} and {chile-pasilla}: stem, seed and toast whole chiles for seconds per side on a dry comal, then soak in hot broth for 20 minutes (if using powders, just whisk them into the broth).",
      "In a little lard, separately fry the sesame seeds (save some for garnish), almonds, raisins, torn tortillas, {canela}, cloves, peppercorns and anise until fragrant.",
      "Char the tomatoes, tomatillos, remaining onion and garlic. Blend everything with the chiles and enough broth into a very smooth paste, in batches.",
      "Fry the paste in hot lard in a heavy pot, stirring constantly, for 10 minutes. Add the {mexican-chocolate} and broth to a gravy consistency, then simmer 45 minutes, seasoning with salt and a little sugar.",
      "Add the chicken to the mole to heat through. Serve sprinkled with sesame seeds, with rice and warm tortillas.",
    ],
    tips: [
      "Toast chiles for seconds only — burnt chiles make mole bitter.",
      "Mole freezes beautifully, so make a double batch.",
    ],
  },
  {
    id: "arepas",
    name: "Arepas Reina Pepiada",
    aliases: ["arepa", "arepas", "reina pepiada", "arepas con queso", "venezuelan arepas", "colombian arepas"],
    cuisine: "Venezuelan",
    country: "Venezuela",
    region: "Latin America",
    flag: "🇻🇪",
    image: null,
    description: "Crispy Venezuelan corn cakes split open and stuffed with avocado chicken salad or melty white cheese.",
    servings: 4, prep: 20, cook: 25, difficulty: "Easy",
    ingredients: [
      k("masarepa", "2 cups"),
      k("queso-llanero", "1 cup shredded"),
      c("Boneless chicken breast", "1 lb", "Meat & Seafood", 5.99),
      c("Ripe avocados", "2", "Produce", 2.5),
      c("Mayonnaise", "3 tbsp", "Condiments", 3.99),
      c("Lime", "1", "Produce", 0.5),
      c("Cilantro", "½ bunch", "Produce", 0.99),
      c("Red onion", "¼", "Produce", 0.99),
      c("Unsalted butter", "2 tbsp", "Dairy", 4.49),
      p("Warm water", "2½ cups"),
      p("Salt", "1½ tsp"),
    ],
    steps: [
      "Poach the chicken in salted water for 15 minutes, then cool and shred finely.",
      "Mash the avocados with the mayonnaise, lime juice, minced onion and chopped cilantro; fold in the chicken and season — that's your reina pepiada.",
      "Stir the salt into the warm water, then gradually work in the {masarepa} until a soft, smooth dough forms. Rest 5 minutes.",
      "Shape into 8 discs about ½-inch thick. Cook on a buttered griddle over medium heat 6–7 minutes per side until crusty and hollow-sounding when tapped.",
      "Split the arepas and stuff half with reina pepiada and half with butter and {queso-llanero}. Eat hot.",
    ],
    tips: [
      "If the dough cracks at the edges while shaping, add a splash more warm water.",
      "Finish arepas in a 375°F oven for 10 minutes for an extra-crisp shell.",
    ],
  },
  {
    id: "lomo-saltado",
    name: "Lomo Saltado",
    aliases: ["lomo saltado", "peruvian stir fry", "saltado"],
    cuisine: "Peruvian",
    country: "Peru",
    region: "Latin America",
    flag: "🇵🇪",
    image: null,
    description: "A sizzling Chinese-Peruvian stir-fry of beef, onions, tomatoes and ají amarillo, tossed with French fries.",
    servings: 4, prep: 20, cook: 20, difficulty: "Easy",
    ingredients: [
      c("Beef sirloin", "1½ lb", "Meat & Seafood", 13.49),
      k("aji-amarillo", "2 tbsp"),
      c("Red onion", "1 large", "Produce", 0.99),
      c("Roma tomatoes", "3", "Produce", 1.49),
      c("Soy sauce", "3 tbsp", "International", 2.99),
      c("Red wine vinegar", "2 tbsp", "Oils & Vinegars", 2.79),
      c("Garlic", "4 cloves", "Produce", 0.69),
      c("Ground cumin", "½ tsp", "Spices", 2.99),
      c("Frozen French fries", "1 bag (24 oz)", "Frozen", 3.49),
      c("Cilantro", "½ bunch", "Produce", 0.99),
      c("Long-grain white rice", "2 cups", "Rice & Grains", 2.49),
      p("Vegetable oil", "3 tbsp"),
      p("Salt & pepper", "to taste"),
    ],
    steps: [
      "Bake or fry the French fries until crisp and cook the white rice.",
      "Cut the beef into thick strips and season with salt, pepper and cumin.",
      "Get a wok or cast-iron pan smoking hot. Sear the beef in batches in a little oil for 1–2 minutes so it browns without stewing; set aside.",
      "Stir-fry the garlic and onion wedges for 1 minute, add the tomato wedges and {aji-amarillo}, then splash in the soy sauce and vinegar and let it sizzle hard.",
      "Return the beef, toss in the fries and cilantro, and serve immediately with rice.",
    ],
    tips: [
      "High heat is everything — this is chifa, Peru's Chinese-Peruvian wok cooking.",
      "Add the fries at the very last second so they stay crisp.",
    ],
  },
  {
    id: "feijoada",
    name: "Feijoada",
    aliases: ["feijoada", "feijoada completa", "brazilian black bean stew"],
    cuisine: "Brazilian",
    country: "Brazil",
    region: "Latin America",
    flag: "🇧🇷",
    image: null,
    description: "Brazil's Saturday feast — black beans slow-simmered with smoked and cured meats, served with farofa and oranges.",
    servings: 8, prep: 30, cook: 180, difficulty: "Weekend project",
    ingredients: [
      c("Dried black beans", "1 lb", "Rice & Grains", 1.79),
      k("carne-seca", "1 lb"),
      k("linguica", "1 lb"),
      c("Pork shoulder or ribs", "1½ lb", "Meat & Seafood", 6.99),
      c("Thick-cut bacon", "6 oz", "Meat & Seafood", 5.49),
      c("Yellow onions", "2", "Produce", 1.49),
      c("Garlic", "6 cloves", "Produce", 0.69),
      c("Bay leaves", "3", "Spices", 2.99),
      c("Collard greens", "1 bunch", "Produce", 2.49),
      c("Oranges", "2", "Produce", 1.98),
      k("farofa", "1 cup"),
      c("Long-grain white rice", "2 cups", "Rice & Grains", 2.49),
      p("Olive oil & butter", "3 tbsp"),
      p("Salt & pepper", "to taste"),
    ],
    steps: [
      "Soak the beans overnight. Desalt the {carne-seca} by soaking it in water for 12–24 hours, changing the water 3 times.",
      "Brown the bacon in a large pot, then the cubed pork and sliced {linguica}. Add the onions and garlic and cook until soft.",
      "Add the drained beans, the cubed {carne-seca}, bay leaves and water to cover by 2 inches. Simmer gently for 2½–3 hours, until the beans are creamy and the meats tender.",
      "Mash a ladleful of beans and stir it back in to thicken the stew. Season to taste.",
      "Meanwhile, toast the {farofa} in butter with a little onion until golden, and sauté thin ribbons of collard greens in garlic and oil.",
      "Serve the feijoada with rice, collards, farofa and orange slices.",
    ],
    tips: [
      "The orange slices aren't decoration — they cut through the richness.",
      "A slow cooker works great: 8 hours on low after browning the meats.",
    ],
  },
];
