import type { DishTemplate } from "@/lib/types";
import { c, k, p } from "./helpers";

export const DISHES_ASIA_MIDEAST_EUROPE: DishTemplate[] = [
  {
    id: "pho-bo",
    name: "Phở Bò",
    aliases: ["pho", "phở", "pho bo", "phở bò", "beef pho", "vietnamese beef noodle soup", "beef noodle soup"],
    cuisine: "Vietnamese",
    country: "Vietnam",
    region: "Southeast Asia",
    flag: "🇻🇳",
    image: "/images/pho.jpg",
    description: "Hanoi-style beef noodle soup with a clear, star-anise-scented broth simmered for hours and finished with fresh herbs.",
    servings: 6, prep: 30, cook: 180, difficulty: "Weekend project",
    ingredients: [
      c("Beef marrow & knuckle bones", "4 lb", "Meat & Seafood", 11.99),
      c("Beef brisket", "1 lb", "Meat & Seafood", 7.99),
      c("Beef eye of round (for thin slices)", "½ lb", "Meat & Seafood", 5.49),
      c("Yellow onions", "2", "Produce", 1.49),
      c("Fresh ginger", "4-inch piece", "Produce", 1.29),
      c("Star anise", "5 pods", "Spices", 4.99),
      c("Cinnamon stick", "1", "Spices", 3.49),
      c("Whole cloves", "4", "Spices", 4.29),
      c("Coriander seeds", "1 tbsp", "Spices", 2.99),
      k("black-cardamom", "1 pod"),
      k("rock-sugar", "1 oz"),
      k("fish-sauce", "¼ cup"),
      k("rice-noodles", "1 lb"),
      k("thai-basil", "1 bunch"),
      k("culantro", "1 bunch"),
      k("thai-chili", "3"),
      c("Bean sprouts", "2 cups", "Produce", 1.99),
      c("Limes", "2", "Produce", 1.99),
      c("Scallions & cilantro", "1 bunch each", "Produce", 1.98),
      c("Hoisin & sriracha", "for serving", "International", 5.98),
      p("Salt", "to taste"),
    ],
    steps: [
      "Parboil the bones for 10 minutes, then drain and rinse them — the secret to a crystal-clear broth.",
      "Char the halved onions and ginger directly over a flame or under the broiler until blackened in spots.",
      "Toast the star anise, cinnamon, cloves, coriander seeds and {black-cardamom} in a dry pan until fragrant, then tie them in a spice bag.",
      "Return the bones to a clean pot with 5 quarts of water, the brisket, charred aromatics and {rock-sugar}. Simmer very gently for 3 hours, skimming often; pull the brisket at 1½ hours and add the spice bag for the final hour.",
      "Season the strained broth with {fish-sauce} and salt. Prepare the {rice-noodles} according to the package and slice the eye of round paper-thin.",
      "Divide the noodles, sliced brisket and raw beef among bowls and ladle the boiling broth over to cook the beef. Serve with {thai-basil}, {culantro}, bean sprouts, lime and {thai-chili}.",
    ],
    tips: [
      "Freeze the eye of round for 20 minutes so it slices paper-thin.",
      "Never boil the broth hard — a lazy simmer keeps it clear.",
    ],
  },
  {
    id: "green-curry",
    name: "Thai Green Curry",
    aliases: ["green curry", "thai green curry", "gaeng keow wan", "kaeng khiao wan", "green curry chicken"],
    cuisine: "Thai",
    country: "Thailand",
    region: "Southeast Asia",
    flag: "🇹🇭",
    image: null,
    description: "Creamy, herb-fragrant Thai curry with coconut milk, makrut lime, galangal and Thai basil.",
    servings: 4, prep: 20, cook: 25, difficulty: "Easy",
    ingredients: [
      c("Thai green curry paste", "3 tbsp", "International", 3.99),
      c("Coconut milk", "2 (13.5-oz) cans", "International", 5.58),
      c("Boneless chicken thighs", "1½ lb", "Meat & Seafood", 6.99),
      k("makrut-lime", "6 leaves"),
      k("galangal", "1-inch piece"),
      k("lemongrass", "1 stalk"),
      k("thai-eggplant", "6 (about 2 cups)"),
      k("thai-basil", "1 cup leaves"),
      k("palm-sugar", "1 tbsp"),
      k("fish-sauce", "2 tbsp"),
      k("thai-chili", "2"),
      c("Jasmine rice", "2 cups", "Rice & Grains", 3.99),
      p("Vegetable oil", "1 tbsp"),
    ],
    steps: [
      "Simmer ½ cup of the thick coconut cream in a wok until the oil separates, then fry the curry paste in it for 2 minutes until fragrant.",
      "Add the sliced chicken and stir to coat, then pour in the remaining coconut milk with the {lemongrass}, {galangal} and {makrut-lime}.",
      "Season with {palm-sugar} and {fish-sauce}, add the {thai-eggplant} and simmer 10–12 minutes until the chicken is cooked.",
      "Turn off the heat and stir in the {thai-basil} and sliced {thai-chili}. Serve with jasmine rice.",
    ],
    tips: [
      "Don't shake the coconut cans — scoop the thick cream off the top for frying the paste.",
      "Balance at the end: salty from fish sauce, sweet from sugar, heat from chili.",
    ],
  },
  {
    id: "pad-thai",
    name: "Pad Thai",
    aliases: ["pad thai", "phad thai", "pad thai shrimp", "shrimp pad thai"],
    cuisine: "Thai",
    country: "Thailand",
    region: "Southeast Asia",
    flag: "🇹🇭",
    image: null,
    description: "Bangkok's street-food icon — chewy rice noodles in a sweet-sour tamarind sauce with shrimp, tofu and peanuts.",
    servings: 4, prep: 25, cook: 15, difficulty: "Medium",
    ingredients: [
      k("rice-noodles", "8 oz"),
      k("tamarind", "3 tbsp"),
      k("palm-sugar", "3 tbsp"),
      k("fish-sauce", "3 tbsp"),
      k("dried-shrimp", "2 tbsp"),
      k("garlic-chives", "1 bunch"),
      k("thai-chili", "to taste"),
      c("Large shrimp, peeled", "¾ lb", "Meat & Seafood", 9.99),
      c("Extra-firm tofu", "4 oz", "Refrigerated", 2.49),
      c("Eggs", "2", "Dairy", 3.49),
      c("Shallots", "2", "Produce", 1.99),
      c("Garlic", "3 cloves", "Produce", 0.69),
      c("Bean sprouts", "2 cups", "Produce", 1.99),
      c("Roasted peanuts", "⅓ cup", "Snacks & Nuts", 3.49),
      c("Limes", "2", "Produce", 1.99),
      p("Vegetable oil", "3 tbsp"),
    ],
    steps: [
      "Soak the {rice-noodles} in room-temperature water for 30–45 minutes until pliable but still firm.",
      "Make the sauce: warm the {tamarind}, {palm-sugar} and {fish-sauce} together until dissolved. It should taste sour, sweet and salty all at once.",
      "In a very hot wok, fry the shallots, garlic, diced tofu and {dried-shrimp} in oil for 1 minute. Add the shrimp and cook until just pink.",
      "Add the drained noodles and the sauce and toss until the noodles soften and absorb it, adding a splash of water if needed.",
      "Push the noodles aside, scramble the eggs in the gap, then toss everything with the bean sprouts and cut {garlic-chives}.",
      "Serve with crushed peanuts, lime wedges and {thai-chili} on the side.",
    ],
    tips: [
      "Cook two servings at a time — a crowded wok steams the noodles.",
      "Under-soak the noodles; they finish cooking in the sauce.",
    ],
  },
  {
    id: "kimchi-jjigae",
    name: "Kimchi Jjigae",
    aliases: ["kimchi jjigae", "kimchi stew", "kimchi chigae", "kimchi soup", "kimchi jigae"],
    cuisine: "Korean",
    country: "South Korea",
    region: "East Asia",
    flag: "🇰🇷",
    image: "/images/kimchi-jjigae.jpg",
    description: "The ultimate Korean comfort stew — sour, aged kimchi bubbling with pork, tofu and gochugaru.",
    servings: 4, prep: 15, cook: 30, difficulty: "Easy",
    ingredients: [
      k("kimchi", "2 cups"),
      k("gochugaru", "1 tbsp"),
      k("gochujang", "1 tbsp"),
      k("anchovy-stock", "3 cups"),
      c("Pork belly or shoulder", "½ lb", "Meat & Seafood", 5.99),
      c("Soft or medium tofu", "1 block (14 oz)", "Refrigerated", 2.49),
      c("Yellow onion", "½", "Produce", 0.99),
      c("Scallions", "3", "Produce", 0.99),
      c("Garlic", "3 cloves", "Produce", 0.69),
      c("Toasted sesame oil", "1 tbsp", "International", 3.99),
      k("short-grain-rice", "2 cups, for serving"),
      p("Sugar", "1 tsp"),
    ],
    steps: [
      "Cut the pork into bite-size pieces and the {kimchi} into strips, saving any juice.",
      "Sauté the pork in sesame oil until it renders and browns, then add the kimchi, garlic and sugar. Stir-fry 5 minutes until the kimchi softens.",
      "Stir in the {gochugaru} and {gochujang}, then pour in the {anchovy-stock} and the kimchi juice.",
      "Add the sliced onion, bring to a boil and simmer 15 minutes.",
      "Slide in thick slices of tofu and simmer 5 minutes more. Top with scallions and serve bubbling with {short-grain-rice}.",
    ],
    tips: [
      "Older, sourer kimchi makes the best jjigae.",
      "A slice of American cheese melted on top is a beloved Korean twist.",
    ],
  },
  {
    id: "mapo-tofu",
    name: "Mapo Tofu",
    aliases: ["mapo tofu", "mapo doufu", "ma po tofu", "mabo tofu"],
    cuisine: "Chinese (Sichuan)",
    country: "China",
    region: "East Asia",
    flag: "🇨🇳",
    image: null,
    description: "Silky tofu in a numbing, fiery Sichuan sauce of chili bean paste, fermented black beans and Sichuan pepper.",
    servings: 4, prep: 15, cook: 20, difficulty: "Easy",
    ingredients: [
      c("Soft or silken tofu", "1 lb", "Refrigerated", 2.49),
      c("Ground pork or beef", "¼ lb", "Meat & Seafood", 3.99),
      k("doubanjiang", "2 tbsp"),
      k("douchi", "1 tbsp"),
      k("sichuan-peppercorn", "1½ tsp"),
      k("shaoxing", "1 tbsp"),
      k("chili-crisp", "1 tbsp"),
      c("Garlic", "3 cloves", "Produce", 0.69),
      c("Fresh ginger", "1-inch piece", "Produce", 1.29),
      c("Scallions", "2", "Produce", 0.99),
      c("Chicken broth", "1 cup", "Soups & Broths", 2.99),
      c("Cornstarch", "1 tbsp", "Baking", 1.99),
      c("Soy sauce", "1 tsp", "International", 2.99),
      p("Vegetable oil", "2 tbsp"),
      p("Steamed rice", "for serving"),
    ],
    steps: [
      "Cut the tofu into 1-inch cubes and simmer gently in salted water for 2 minutes to firm it up; drain.",
      "Toast the {sichuan-peppercorn} in a dry wok until fragrant, then grind.",
      "Brown the ground meat in oil until crisp. Add the {doubanjiang} and fry until the oil turns red, then add the {douchi}, garlic and ginger.",
      "Splash in the {shaoxing}, add the broth and soy sauce, and slide in the tofu. Simmer 5 minutes, nudging gently rather than stirring.",
      "Thicken with the cornstarch slurry in two additions. Finish with {chili-crisp}, the ground pepper and scallions. Serve over rice.",
    ],
    tips: [
      "Blanching the tofu in salted water keeps the cubes from breaking.",
      "Push the tofu with the back of your spatula instead of stirring.",
    ],
  },
  {
    id: "okonomiyaki",
    name: "Okonomiyaki",
    aliases: ["okonomiyaki", "japanese pancake", "osaka pancake", "savory cabbage pancake"],
    cuisine: "Japanese",
    country: "Japan",
    region: "East Asia",
    flag: "🇯🇵",
    image: null,
    description: "Osaka's savory cabbage pancake — 'grilled as you like it' — lacquered with sweet sauce, mayo and bonito.",
    servings: 2, prep: 15, cook: 20, difficulty: "Easy",
    ingredients: [
      k("okonomiyaki-flour", "1 cup"),
      k("dashi", "⅔ cup"),
      k("nagaimo", "¼ cup grated"),
      c("Green cabbage", "¼ head", "Produce", 1.99),
      c("Eggs", "2", "Dairy", 3.49),
      c("Pork belly slices or bacon", "6 strips", "Meat & Seafood", 5.99),
      c("Scallions", "2", "Produce", 0.99),
      k("beni-shoga", "2 tbsp"),
      k("okonomi-sauce", "¼ cup"),
      k("kewpie", "2 tbsp"),
      k("aonori", "1 tsp"),
      k("bonito", "a handful"),
      p("Vegetable oil", "1 tbsp"),
    ],
    steps: [
      "Whisk the {okonomiyaki-flour} with the {dashi} and {nagaimo} until smooth; rest 30 minutes in the fridge if you have time.",
      "Fold in the eggs, finely shredded cabbage, scallions and chopped {beni-shoga} — the batter should just coat the cabbage.",
      "Heat oil in a skillet over medium heat. Pile in half the batter, shape into a thick 1-inch round and lay pork belly strips on top.",
      "Cook 5 minutes until golden, flip and cook 5 more minutes (pork side down), then flip again for a final 2 minutes.",
      "Brush with {okonomi-sauce}, zigzag with {kewpie}, and shower with {aonori} and {bonito}.",
    ],
    tips: [
      "Don't press the pancake — its fluffiness comes from trapped air.",
      "Layer in cooked yakisoba noodles for Hiroshima-style.",
    ],
  },
  {
    id: "sinigang",
    name: "Sinigang na Baboy",
    aliases: ["sinigang", "sinigang na baboy", "pork sinigang", "filipino sour soup", "tamarind soup"],
    cuisine: "Filipino",
    country: "Philippines",
    region: "Southeast Asia",
    flag: "🇵🇭",
    image: null,
    description: "The Philippines' beloved sour tamarind soup with tender pork, vegetables and greens — pure comfort in a bowl.",
    servings: 6, prep: 20, cook: 75, difficulty: "Easy",
    ingredients: [
      c("Pork ribs or belly", "2 lb", "Meat & Seafood", 9.99),
      k("sinigang-mix", "1 packet"),
      k("taro", "3 small"),
      k("daikon", "1 medium"),
      k("long-beans", "1 bunch"),
      k("kangkong", "1 bunch"),
      c("Roma tomatoes", "3", "Produce", 1.49),
      c("Yellow onion", "1", "Produce", 0.99),
      c("Long green chilies or jalapeños", "3", "Produce", 0.99),
      c("Japanese eggplant", "1", "Produce", 1.49),
      k("fish-sauce", "2 tbsp"),
      p("Water", "8 cups"),
      p("Steamed rice", "for serving"),
    ],
    steps: [
      "Bring the pork, quartered tomatoes and onion to a boil in 8 cups of water; skim the scum, then simmer 45–60 minutes until tender.",
      "Add the peeled, halved {taro} and cook 10 minutes until soft — some will melt into the broth and thicken it.",
      "Add the sliced {daikon} and simmer 5 minutes, then the {long-beans}, eggplant and green chilies for 3 minutes.",
      "Stir in the {sinigang-mix} and season with {fish-sauce}. Taste: it should be boldly sour.",
      "Turn off the heat and add the {kangkong}, letting it wilt in the hot broth. Serve with steamed rice.",
    ],
    tips: [
      "Sinigang should make you pucker — keep adding sourness until it's bright.",
      "Dip the pork in fish sauce with crushed chili on the side.",
    ],
  },
  {
    id: "nasi-goreng",
    name: "Nasi Goreng",
    aliases: ["nasi goreng", "indonesian fried rice", "nasi goreng ayam"],
    cuisine: "Indonesian",
    country: "Indonesia",
    region: "Southeast Asia",
    flag: "🇮🇩",
    image: null,
    description: "Indonesia's sweet, smoky fried rice glazed with kecap manis and shrimp paste, crowned with a fried egg.",
    servings: 4, prep: 15, cook: 15, difficulty: "Easy",
    ingredients: [
      c("Cooked jasmine rice (day-old)", "4 cups", "Rice & Grains", 3.99),
      k("kecap-manis", "3 tbsp"),
      k("shrimp-paste", "1 tsp"),
      k("thai-chili", "2–3"),
      c("Shallots", "4", "Produce", 1.99),
      c("Garlic", "3 cloves", "Produce", 0.69),
      c("Boneless chicken thighs or shrimp", "¾ lb", "Meat & Seafood", 5.99),
      c("Eggs", "4", "Dairy", 3.49),
      c("Sambal oelek", "1 tbsp", "International", 3.29),
      c("Cucumber & tomato", "1 each", "Produce", 1.98),
      k("birista", "¼ cup"),
      c("Soy sauce", "1 tbsp", "International", 2.99),
      p("Vegetable oil", "3 tbsp"),
    ],
    steps: [
      "Pound or blend the shallots, garlic, {thai-chili} and {shrimp-paste} into a rough paste (bumbu).",
      "Fry the bumbu in oil over medium-high heat for 2 minutes until fragrant and darkened.",
      "Add the diced chicken or shrimp and stir-fry until cooked through.",
      "Add the cold rice, breaking up clumps, then the {kecap-manis}, soy sauce and sambal. Toss over high heat until every grain is glossy and slightly smoky.",
      "Fry the eggs sunny-side up. Serve the rice topped with a fried egg, {birista} and sliced cucumber and tomato.",
    ],
    tips: [
      "Day-old rice is a must — fresh rice turns mushy.",
      "Add prawn crackers on the side for the full warung experience.",
    ],
  },
  {
    id: "chicken-biryani",
    name: "Hyderabadi Chicken Biryani",
    aliases: ["biryani", "chicken biryani", "hyderabadi biryani", "dum biryani", "biriyani", "briyani"],
    cuisine: "Indian",
    country: "India",
    region: "South Asia",
    flag: "🇮🇳",
    image: "/images/biryani.jpg",
    description: "Layered Hyderabadi dum biryani — saffron basmati and spiced chicken sealed and steamed until fragrant.",
    servings: 6, prep: 45, cook: 60, difficulty: "Weekend project",
    ingredients: [
      c("Bone-in chicken thighs", "2½ lb", "Meat & Seafood", 7.99),
      c("Aged basmati rice", "3 cups", "Rice & Grains", 6.99),
      c("Plain whole-milk yogurt", "1 cup", "Dairy", 2.49),
      k("birista", "1½ cups"),
      k("biryani-masala", "2 tbsp"),
      k("kashmiri-chili", "2 tsp"),
      k("green-chili", "4"),
      k("shahi-jeera", "1 tsp"),
      k("black-cardamom", "2 pods"),
      k("mace", "1 blade"),
      k("saffron", "a generous pinch"),
      k("kewra", "1 tsp"),
      k("ghee", "¼ cup"),
      c("Ginger-garlic paste", "2 tbsp", "International", 3.49),
      c("Green cardamom, cloves, cinnamon & bay leaves", "a few of each", "Spices", 6.99),
      c("Fresh mint & cilantro", "1 bunch each", "Produce", 3.48),
      c("Lemon", "1", "Produce", 0.79),
      c("Whole milk", "¼ cup", "Dairy", 1.99),
      p("Salt", "to taste"),
    ],
    steps: [
      "Marinate the chicken with the yogurt, ginger-garlic paste, {biryani-masala}, {kashmiri-chili}, slit {green-chili}, half the {birista}, half the mint and cilantro, lemon juice, 2 tbsp {ghee} and salt for at least 2 hours.",
      "Soak the rice for 30 minutes. Warm the milk and steep the {saffron} in it.",
      "Boil a big pot of heavily salted water with the whole spices, {shahi-jeera}, {black-cardamom} and {mace}. Par-cook the rice for 5–6 minutes until about 70% done; drain.",
      "Spread the chicken in a heavy pot and layer the rice on top, then drizzle with the saffron milk, {kewra}, the remaining {ghee}, {birista} and herbs.",
      "Seal the pot tightly with foil and the lid (dum). Cook on high for 5 minutes, then on the lowest heat for 40 minutes.",
      "Rest 10 minutes, then gently mix the layers from the side as you serve with raita.",
    ],
    tips: [
      "The rice must be only 70% cooked before layering — it finishes in the steam.",
      "Set a flat griddle under the pot during dum to prevent scorching.",
    ],
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    aliases: ["palak paneer", "saag paneer", "spinach paneer", "palak panir"],
    cuisine: "Indian",
    country: "India",
    region: "South Asia",
    flag: "🇮🇳",
    image: null,
    description: "Velvety North Indian spinach curry with seared paneer, warm spices and a hint of fenugreek.",
    servings: 4, prep: 15, cook: 30, difficulty: "Easy",
    ingredients: [
      k("paneer", "14 oz"),
      c("Fresh spinach", "1½ lb", "Produce", 6.98),
      c("Yellow onion", "1", "Produce", 0.99),
      c("Roma tomato", "1", "Produce", 0.5),
      c("Garlic", "4 cloves", "Produce", 0.69),
      c("Fresh ginger", "1-inch piece", "Produce", 1.29),
      k("green-chili", "2"),
      k("ghee", "3 tbsp"),
      c("Cumin seeds", "1 tsp", "Spices", 3.49),
      c("Garam masala", "1 tsp", "Spices", 4.49),
      k("kashmiri-chili", "½ tsp"),
      k("kasuri-methi", "1 tbsp"),
      c("Heavy cream", "3 tbsp", "Dairy", 3.49),
      p("Salt", "to taste"),
    ],
    steps: [
      "Blanch the spinach in boiling water for 1 minute, plunge into ice water, then blend with the {green-chili} to a smooth purée.",
      "Cube the {paneer} and sear in 1 tbsp {ghee} until golden on a couple of sides; set aside.",
      "Heat the remaining {ghee}, crackle the cumin seeds, then cook the onion until golden. Add the garlic, ginger and tomato and cook until jammy.",
      "Stir in the {kashmiri-chili} and garam masala, then the spinach purée. Simmer 5 minutes — any longer and it turns dull.",
      "Stir in {kasuri-methi}, the cream and the paneer and simmer 2 minutes. Serve with naan or rice.",
    ],
    tips: [
      "The ice bath keeps the spinach vivid green.",
      "Soak seared paneer in warm water for 5 minutes for an extra-soft texture.",
    ],
  },
  {
    id: "ghormeh-sabzi",
    name: "Ghormeh Sabzi",
    aliases: ["ghormeh sabzi", "khoresh ghormeh sabzi", "persian herb stew", "ghormeh sabzi stew", "qormeh sabzi"],
    cuisine: "Persian",
    country: "Iran",
    region: "Middle East",
    flag: "🇮🇷",
    image: null,
    description: "Iran's beloved herb stew — slow-fried greens, tender meat, kidney beans and tangy dried limes.",
    servings: 6, prep: 30, cook: 180, difficulty: "Weekend project",
    ingredients: [
      c("Beef or lamb stew meat", "1½ lb", "Meat & Seafood", 10.99),
      c("Kidney beans (canned)", "1 (15-oz) can", "Canned Goods", 1.19),
      c("Fresh parsley", "2 bunches", "Produce", 1.98),
      c("Fresh cilantro", "1 bunch", "Produce", 0.99),
      c("Scallions or chives", "1 bunch", "Produce", 0.99),
      k("kasuri-methi", "2 tbsp"),
      k("dried-lime", "4"),
      c("Yellow onion", "1 large", "Produce", 0.99),
      c("Ground turmeric", "1 tsp", "Spices", 2.99),
      c("Lemon", "1", "Produce", 0.79),
      c("Basmati rice", "2 cups", "Rice & Grains", 4.99),
      k("saffron", "a pinch, for the rice"),
      p("Vegetable oil", "½ cup"),
      p("Salt & pepper", "to taste"),
    ],
    steps: [
      "Finely chop the parsley, cilantro and scallions. Fry them in ¼ cup oil over medium-low heat for 15–20 minutes until dark green and fragrant, adding {kasuri-methi} in the last 2 minutes.",
      "In a separate pot, brown the diced onion in oil, add the turmeric and the meat, and sear until browned.",
      "Add the fried herbs, 4 cups of water and the {dried-lime} (pierce whole dried limes with a knife; if using fresh lime, add it in the last 20 minutes instead). Cover and simmer gently for 2½ hours.",
      "Add the drained kidney beans and simmer 30 minutes more, until the stew is thick and the oil rises to the top. Finish with lemon juice and salt.",
      "Serve with fluffy basmati rice finished with {saffron} water.",
    ],
    tips: [
      "Frying the herbs low and slow is the heart of ghormeh sabzi — they should turn almost black-green.",
      "Like most stews, it's even better the next day.",
    ],
  },
  {
    id: "mansaf",
    name: "Mansaf",
    aliases: ["mansaf", "jordanian mansaf", "lamb mansaf"],
    cuisine: "Jordanian",
    country: "Jordan",
    region: "Middle East",
    flag: "🇯🇴",
    image: null,
    description: "Jordan's national dish of tender lamb cooked in tangy jameed yogurt sauce, served over rice and shrak bread.",
    servings: 6, prep: 30, cook: 150, difficulty: "Weekend project",
    ingredients: [
      c("Bone-in lamb shoulder, in chunks", "3 lb", "Meat & Seafood", 23.99),
      k("jameed", "1 lb"),
      k("shrak", "2 large sheets"),
      k("baharat", "1 tbsp"),
      k("ghee", "3 tbsp"),
      c("Medium-grain rice (Calrose)", "3 cups", "Rice & Grains", 3.99),
      c("Yellow onion", "1", "Produce", 0.99),
      c("Bay leaves & cardamom pods", "3 each", "Spices", 4.99),
      c("Ground turmeric", "½ tsp", "Spices", 2.99),
      c("Slivered almonds & pine nuts", "½ cup", "Snacks & Nuts", 6.99),
      c("Fresh parsley", "½ bunch", "Produce", 0.99),
      p("Salt", "to taste"),
    ],
    steps: [
      "Cover the lamb with water, bring to a boil and skim. Add the halved onion, bay leaves, cardamom and {baharat}, then simmer 1½–2 hours until tender.",
      "Blend the {jameed} smooth with some of the lamb broth. Bring it slowly to a simmer in a large pot, stirring constantly in one direction so it doesn't split.",
      "Move the lamb into the sauce and simmer together for 20–30 minutes.",
      "Cook the rice with the turmeric, a spoon of {ghee} and salt. Toast the almonds and pine nuts in the remaining ghee.",
      "Line a large platter with {shrak}, moisten it with sauce, pile on the rice and lamb, and finish with the nuts, parsley and extra sauce on the side.",
    ],
    tips: [
      "Stir the sauce constantly while it heats — it's the difference between silky and grainy.",
      "Mansaf is traditionally eaten standing, with the right hand, from a shared platter.",
    ],
  },
  {
    id: "chicken-tagine",
    name: "Chicken Tagine with Preserved Lemon",
    aliases: ["tagine", "chicken tagine", "moroccan chicken", "djaj mqualli", "tajine", "chicken tajine"],
    cuisine: "Moroccan",
    country: "Morocco",
    region: "North Africa",
    flag: "🇲🇦",
    image: null,
    description: "A fragrant Moroccan braise of chicken, preserved lemon and green olives, perfumed with ras el hanout and saffron.",
    servings: 4, prep: 20, cook: 75, difficulty: "Medium",
    ingredients: [
      c("Bone-in chicken thighs", "2½ lb", "Meat & Seafood", 7.99),
      k("preserved-lemon", "1"),
      k("ras-el-hanout", "2 tsp"),
      k("saffron", "a pinch"),
      c("Green olives", "¾ cup", "Deli", 4.99),
      c("Yellow onions", "2", "Produce", 1.49),
      c("Garlic", "4 cloves", "Produce", 0.69),
      c("Fresh ginger", "1-inch piece", "Produce", 1.29),
      c("Ground turmeric", "½ tsp", "Spices", 2.99),
      c("Cilantro & parsley", "1 bunch each", "Produce", 1.98),
      c("Couscous", "1½ cups", "Rice & Grains", 2.99),
      p("Olive oil", "¼ cup"),
      p("Salt & pepper", "to taste"),
    ],
    steps: [
      "Rub the chicken with grated garlic and ginger, {ras-el-hanout}, turmeric, crumbled {saffron}, olive oil, salt and pepper. Marinate 30 minutes or overnight.",
      "Brown the chicken skin-side down in a tagine or Dutch oven; remove. Cook the sliced onions in the fat until soft and golden.",
      "Return the chicken, add 1 cup of water and a handful of herbs, cover and simmer gently for 45 minutes.",
      "Add the olives and slivered {preserved-lemon} and cook uncovered for 15 minutes until the sauce thickens.",
      "Scatter with the remaining herbs and serve with fluffy couscous or crusty bread.",
    ],
    tips: [
      "Use only the rind of preserved lemon — rinse it if it's very salty.",
      "Season gently at first; olives and preserved lemon add plenty of salt.",
    ],
  },
  {
    id: "pierogi",
    name: "Pierogi Ruskie",
    aliases: ["pierogi", "pierogies", "perogies", "pierogi ruskie", "potato cheese pierogi", "varenyky", "vareniki"],
    cuisine: "Polish",
    country: "Poland",
    region: "Europe",
    flag: "🇵🇱",
    image: null,
    description: "Polish dumplings stuffed with potato, farmer's cheese and caramelized onion, finished with butter and smetana.",
    servings: 6, prep: 60, cook: 30, difficulty: "Weekend project",
    ingredients: [
      c("All-purpose flour", "3½ cups", "Baking", 2.99),
      c("Egg", "1", "Dairy", 3.49),
      k("smetana", "1 cup"),
      c("Russet potatoes", "2 lb", "Produce", 3.49),
      k("twarog", "8 oz"),
      c("Yellow onions", "2", "Produce", 1.49),
      c("Unsalted butter", "4 tbsp", "Dairy", 4.49),
      p("Warm water", "¾ cup"),
      p("Salt & black pepper", "to taste"),
    ],
    steps: [
      "Make the dough: mix the flour, egg, ½ cup of the {smetana}, warm water and a pinch of salt; knead until smooth, cover and rest 30 minutes.",
      "Boil the potatoes until tender, then mash. Fry one finely diced onion in butter until golden and mix it into the potatoes with the crumbled {twarog}, plenty of pepper and salt.",
      "Roll the dough thin, cut 3-inch rounds, fill each with a spoonful of filling and pinch the edges firmly closed.",
      "Boil in batches in salted water; once they float, cook 2 minutes more.",
      "Fry the second onion in butter until caramelized. Toss the pierogi in it and serve with the rest of the {smetana}.",
    ],
    tips: [
      "Freeze uncooked pierogi on a tray, then bag them — cook straight from frozen.",
      "Pan-fry boiled leftovers in butter the next day for crispy edges.",
    ],
  },
  {
    id: "khachapuri",
    name: "Khachapuri Adjaruli",
    aliases: ["khachapuri", "khachapuri adjaruli", "adjarian khachapuri", "georgian cheese bread", "acharuli"],
    cuisine: "Georgian",
    country: "Georgia",
    region: "Caucasus",
    flag: "🇬🇪",
    image: null,
    description: "Georgia's boat-shaped cheese bread with a molten pool of cheese, a runny egg and a pat of butter.",
    servings: 4, prep: 20, cook: 20, difficulty: "Medium",
    ingredients: [
      c("All-purpose flour", "3 cups", "Baking", 2.99),
      c("Active dry yeast", "1 packet", "Baking", 1.49),
      c("Whole milk", "1 cup", "Dairy", 1.99),
      c("Sugar", "1 tsp", "Baking", 2.99),
      k("sulguni", "12 oz shredded"),
      c("Eggs", "3", "Dairy", 3.49),
      c("Unsalted butter", "2 tbsp", "Dairy", 4.49),
      p("Salt", "1 tsp"),
      p("Olive oil", "1 tbsp"),
    ],
    steps: [
      "Warm the milk, stir in the yeast and sugar and let it foam for 5 minutes. Mix with the flour, salt and oil and knead into a soft dough. Let rise for 1 hour.",
      "Mix the {sulguni} with 1 beaten egg.",
      "Divide the dough in two and roll into ovals. Roll up the long edges and twist the ends to form boat shapes.",
      "Fill the boats with the cheese and bake at 475°F for 12–15 minutes until golden.",
      "Make a well in the cheese, crack an egg into each, and bake 2–3 minutes more until the white just sets. Top with butter and stir at the table.",
    ],
    tips: [
      "Tear off the crust and swirl it through the molten egg and cheese.",
      "Pull it while the yolk is still runny — it keeps cooking in the hot cheese.",
    ],
  },
];
