import type { SpecialtyIngredient } from "@/lib/types";
import { AFCAR, INTL, LATIN, LATSPEC, M, NAT, b, ing, s } from "./helpers";

/** West & East African, Caribbean and Latin American specialty ingredients. */
export const AMERICAS_AFRICA: SpecialtyIngredient[] = [
  /* ---------------- West & East Africa ---------------- */
  ing("scotch-bonnet", "Scotch bonnet peppers", "scotch bonnet peppers",
    ["scotch bonnet", "scotch bonnets", "scotch bonnet pepper", "ata rodo", "bonney pepper"],
    ["Nigerian", "Ghanaian", "Jamaican", "Trinidadian"], "Produce", [...AFCAR, ...LATSPEC],
    b("Scotch bonnet peppers", "Produce", 2.49), [
      s("Habanero peppers", "habanero peppers", 92, M, [b("Habanero peppers", "Produce", 1.29)],
        "1:1 — same count", "Habaneros are the same species (Capsicum chinense) with nearly identical fruity heat; scotch bonnets are just a touch sweeter."),
      s("Serrano peppers + pinch of cayenne", "serrano peppers and a pinch of cayenne", 66, M,
        [b("Serrano peppers", "Produce", 0.99), b("Ground cayenne pepper", "Spices", 2.49)],
        "2 serranos + ⅛ tsp cayenne per bonnet", "Matches the heat level but misses the tropical, apricot-like aroma."),
    ]),
  ing("palm-oil", "Red palm oil", "red palm oil",
    ["red palm oil", "palm oil", "zomi", "manja", "dende", "azeite de dendê"],
    ["Nigerian", "Ghanaian", "Brazilian"], "Pantry", [...AFCAR, ...NAT],
    b("Red palm oil", "Oils & Vinegars", 8.99), [
      s("Annatto-infused vegetable oil", "annatto oil (vegetable oil steeped with annatto seeds)", 80, [...LATIN, ...INTL],
        [b("Annatto (achiote) seeds", "International", 2.49), b("Vegetable oil", "Oils & Vinegars", 3.99)],
        "Warm ½ cup oil with 1 tbsp annatto seeds for 5 min, then strain", "Annatto gives the same brick-red color plus an earthy, peppery note close to palm oil."),
      s("Vegetable oil + sweet paprika + turmeric", "vegetable oil tinted with paprika and turmeric", 68, M,
        [b("Vegetable oil", "Oils & Vinegars", 3.99), b("Sweet paprika", "Spices", 2.99), b("Ground turmeric", "Spices", 2.99)],
        "½ cup oil + 1 tsp paprika + ¼ tsp turmeric", "Nails the color; the flavor is milder, so lean on stock and bouillon."),
    ]),
  ing("egusi", "Ground egusi (melon seeds)", "ground egusi",
    ["egusi", "egusi seeds", "ground egusi", "melon seeds", "agushi"],
    ["Nigerian", "Ghanaian"], "Pantry", AFCAR, b("Ground egusi", "International", 9.99), [
      s("Raw pepitas, finely ground", "ground pepitas (pumpkin seeds)", 85, M, [b("Raw hulled pumpkin seeds (pepitas)", "Snacks & Nuts", 4.99)],
        "1:1 by volume — pulse to a fine meal", "Pepitas are close botanical cousins and clump into the same curd-like texture when fried."),
      s("Raw sunflower seeds, ground", "ground sunflower seeds", 70, M, [b("Raw sunflower kernels", "Snacks & Nuts", 3.49)],
        "1:1 by volume", "Rich and nutty; slightly more bitter, so toast lightly first."),
    ]),
  ing("iru", "Iru (fermented locust beans)", "iru",
    ["iru", "dawadawa", "locust beans", "ogiri", "soumbala"],
    ["Nigerian", "Ghanaian"], "Sauce & Paste", AFCAR, b("Iru (frozen fermented locust beans)", "Frozen", 6.99), [
      s("Miso paste", "miso paste", 72, [...INTL, ...NAT, "asian"], [b("Miso paste", "International", 5.49)],
        "1 tbsp miso per 1 tbsp iru", "Another fermented legume paste — it brings the same funky, savory depth."),
      s("Soy sauce + extra bouillon", "soy sauce plus extra bouillon", 56, M, [b("Soy sauce", "International", 2.99)],
        "2 tsp soy sauce per tbsp iru", "Umami without the funk — works when nothing else is available."),
    ]),
  ing("ground-crayfish", "Ground dried crayfish", "ground crayfish",
    ["crayfish", "ground crayfish", "dried crayfish", "crayfish powder"],
    ["Nigerian", "Ghanaian", "Cameroonian"], "Spice & Seasoning", AFCAR, b("Ground dried crayfish", "International", 7.99), [
      s("Dried shrimp, ground", "ground dried shrimp", 88, ["asian", "latin"], [b("Dried shrimp (camarón seco)", "International", 4.99)],
        "1:1 after grinding", "Nearly identical smoky-briny flavor — West African 'crayfish' is actually tiny dried shrimp."),
      s("Anchovy paste + smoked paprika", "anchovy paste with a pinch of smoked paprika", 64, M,
        [b("Anchovy paste (tube)", "Canned Goods", 3.29), b("Smoked paprika", "Spices", 3.49)],
        "1 tsp anchovy paste + ¼ tsp smoked paprika per tbsp", "Delivers the savory sea-funk and a whisper of smoke."),
    ]),
  ing("stockfish", "Stockfish (dried cod)", "stockfish",
    ["stockfish", "okporoko", "panla", "dried fish", "smoked fish", "smoked catfish"],
    ["Nigerian", "Ghanaian"], "Protein", AFCAR, b("Stockfish pieces", "International", 12.99), [
      s("Salt cod (bacalao)", "soaked salt cod", 82, [...LATIN, ...INTL], [b("Salt cod (bacalao)", "Meat & Seafood", 9.99)],
        "Soak overnight, changing water twice; 1:1", "The same cod, preserved with salt instead of air-drying — firm, flaky and deeply savory."),
      s("Smoked turkey wings", "smoked turkey", 70, M, [b("Smoked turkey wings", "Meat & Seafood", 6.49)],
        "1 lb per ½ lb stockfish", "A Southern staple that gives the soup the smoky depth stockfish brings."),
    ]),
  ing("ugu", "Ugu (fluted pumpkin leaves)", "ugu leaves",
    ["ugu", "pumpkin leaves", "bitter leaf", "bitterleaf", "efo", "waterleaf", "utazi"],
    ["Nigerian"], "Produce", AFCAR, b("Ugu leaves (frozen)", "Frozen", 5.99), [
      s("Spinach + a little kale", "spinach and kale", 80, M, [b("Fresh spinach", "Produce", 3.49), b("Kale", "Produce", 2.49)],
        "2 parts spinach : 1 part kale", "Spinach brings the tenderness, kale the gentle bitterness and body of ugu."),
      s("Collard greens", "thinly sliced collard greens", 72, M, [b("Collard greens", "Produce", 2.49)],
        "1:1, sliced thin", "Holds up to long simmering like bitter leaf."),
    ]),
  ing("maggi", "Maggi seasoning cubes", "Maggi cubes",
    ["maggi", "maggi cube", "maggi cubes", "maggi seasoning", "seasoning cube", "seasoning cubes"],
    ["Nigerian", "Ghanaian", "Senegalese", "Cameroonian"], "Spice & Seasoning", [...INTL, ...LATIN, ...AFCAR],
    b("Maggi seasoning cubes", "International", 2.99), [
      s("Knorr chicken bouillon cubes", "chicken bouillon cubes", 90, M, [b("Knorr chicken bouillon cubes", "Soups & Broths", 2.49)],
        "1:1", "The same savory, MSG-forward profile most West African cooks rely on."),
    ]),
  ing("nigerian-curry", "Nigerian/Caribbean curry powder", "curry powder",
    ["nigerian curry", "nigerian curry powder", "ducros curry", "tropical sun curry", "jamaican curry powder", "caribbean curry powder"],
    ["Nigerian", "Jamaican", "Ghanaian"], "Spice & Seasoning", AFCAR, b("Nigerian/Caribbean curry powder", "International", 4.49), [
      s("Mild curry powder + extra turmeric", "mild curry powder with extra turmeric", 88, M,
        [b("Mild curry powder (McCormick)", "Spices", 3.99), b("Ground turmeric", "Spices", 2.99)],
        "1:1 plus ¼ tsp turmeric", "West African and Caribbean curry blends are turmeric-heavy and mild — this gets you there."),
    ]),
  ing("pounded-yam", "Pounded yam flour (poundo iyan)", "pounded yam",
    ["pounded yam", "poundo", "poundo yam", "iyan", "fufu", "fufu flour", "garri", "eba", "semovita"],
    ["Nigerian", "Ghanaian"], "Grain & Flour", AFCAR, b("Poundo yam flour", "International", 8.99), [
      s("Cassava flour", "cassava flour swallow", 82, NAT, [b("Cassava flour (Bob's Red Mill)", "Baking", 7.99)],
        "Stir 1 cup into 1¼ cups boiling water until smooth and stretchy", "Cassava is the base of many fufus — it gives a smooth, stretchy swallow."),
      s("Instant potato flakes + potato starch", "potato-flake fufu", 74, M,
        [b("Instant mashed potato flakes", "Pantry", 2.49), b("Potato starch", "Baking", 3.49)],
        "2 cups flakes + ½ cup starch stirred into boiling water", "A beloved diaspora hack — the starch gives fufu its signature stretch."),
    ]),
  ing("berbere", "Berbere spice blend", "berbere",
    ["berbere", "berbere spice", "berebere"],
    ["Ethiopian", "Eritrean"], "Spice & Seasoning", [...AFCAR, ...NAT], b("Berbere", "Spices", 6.99), [
      s("DIY berbere", "homemade berbere (paprika, cayenne, ginger, cardamom, cinnamon & cloves)", 78, M,
        [b("Sweet paprika", "Spices", 2.99), b("Ground cayenne pepper", "Spices", 2.49), b("Ground ginger", "Spices", 3.29), b("Ground cardamom", "Spices", 6.99)],
        "¼ cup paprika + 1 tbsp cayenne + 1 tsp each ginger & cardamom + ½ tsp cinnamon + ¼ tsp cloves",
        "Berbere's backbone is chili plus warm spices — toast the blend in butter to deepen it."),
    ]),
  ing("niter-kibbeh", "Niter kibbeh (spiced butter)", "niter kibbeh",
    ["niter kibbeh", "niter kebbeh", "spiced butter", "tesmi"],
    ["Ethiopian", "Eritrean"], "Dairy", AFCAR, b("Niter kibbeh", "Refrigerated", 9.99), [
      s("Homemade spiced clarified butter", "homemade spiced butter (simmered with garlic, ginger, cardamom & turmeric)", 88, M,
        [b("Unsalted butter", "Dairy", 4.49), b("Ground turmeric", "Spices", 2.99)],
        "Simmer 1 cup butter 20 min with 2 garlic cloves, 1 tbsp ginger, ½ tsp cardamom, ¼ tsp turmeric; strain",
        "This is exactly how niter kibbeh is made at home in Addis."),
    ]),
  ing("teff", "Teff flour (for injera)", "teff flour",
    ["teff", "teff flour", "injera", "injera flour"],
    ["Ethiopian", "Eritrean"], "Grain & Flour", [...AFCAR, ...NAT], b("Teff flour", "Baking", 9.99), [
      s("Buckwheat + all-purpose flour (quick injera)", "a quick buckwheat & all-purpose flour batter", 62, M,
        [b("Buckwheat flour", "Baking", 5.99), b("All-purpose flour", "Baking", 2.99), b("Club soda", "Beverages", 1.29)],
        "1 cup buckwheat + 1 cup AP flour + 2½ cups club soda; rest 1 hour", "Buckwheat brings the earthy tang, club soda the spongy 'eyes'."),
    ]),

  /* ---------------- Caribbean ---------------- */
  ing("pimento-wood", "Pimento wood", "pimento wood",
    ["pimento wood", "pimento sticks", "pimento leaves", "pimento chips"],
    ["Jamaican"], "Pantry", AFCAR, b("Pimento wood chips", "International", 14.99), [
      s("Hickory chips + whole allspice berries", "hickory chips scattered with whole allspice berries", 80, M,
        [b("Hickory smoking chips", "Grilling", 5.99), b("Whole allspice", "Spices", 4.49)],
        "Soak 2 cups chips with 2 tbsp allspice berries", "Allspice IS pimento — the berries recreate the aromatic jerk smoke on any grill."),
      s("Liquid smoke + extra allspice", "liquid smoke with extra allspice", 60, M, [b("Liquid smoke", "Condiments", 2.99)],
        "¼ tsp liquid smoke in the marinade", "For oven-roasted jerk — smoke without a grill."),
    ]),
  ing("browning", "Browning sauce", "browning",
    ["browning", "browning sauce", "grace browning"],
    ["Jamaican", "Trinidadian", "Guyanese"], "Sauce & Paste", [...AFCAR, ...LATSPEC], b("Browning sauce (Grace)", "International", 3.49), [
      s("Kitchen Bouquet", "Kitchen Bouquet", 90, M, [b("Kitchen Bouquet browning sauce", "Condiments", 3.99)],
        "1:1", "It's essentially the same caramel-based browning product."),
      s("Soy sauce + molasses", "soy sauce mixed with molasses", 70, M, [b("Molasses", "Baking", 3.99)],
        "1 tsp soy + 1 tsp molasses per tsp browning", "Deep color with the same bittersweet edge."),
    ]),
  ing("sour-orange", "Sour orange (naranja agria)", "sour orange juice",
    ["sour orange", "sour orange juice", "naranja agria", "bitter orange", "seville orange"],
    ["Cuban", "Puerto Rican", "Dominican", "Haitian", "Yucatecan"], "Produce", [...LATIN, ...AFCAR],
    b("Sour orange juice (Goya Naranja Agria)", "International", 2.99), [
      s("Orange juice + lime juice", "orange juice mixed with lime juice (2:1)", 88, M,
        [b("Orange juice (not from concentrate)", "Dairy & Juice", 3.99), b("Limes", "Produce", 1.99)],
        "⅔ cup OJ + ⅓ cup lime juice per cup", "The classic mojo hack — sweet-tart and bright like true sour orange."),
    ]),

  /* ---------------- Latin America ---------------- */
  ing("culantro", "Culantro (recao / ngò gai)", "culantro",
    ["culantro", "recao", "ngo gai", "ngò gai", "sawtooth coriander", "sawtooth herb", "shado beni", "chadon beni", "long coriander"],
    ["Puerto Rican", "Cuban", "Vietnamese", "Trinidadian", "Thai"], "Fresh Herb", ["asian", "latin_specialty"], b("Fresh culantro", "Produce", 1.99), [
      s("Cilantro with stems", "extra cilantro (stems included)", 82, M, [b("Cilantro", "Produce", 0.99)],
        "1½× the amount, added later in cooking", "Same flavor family — culantro is just stronger, so use more cilantro."),
    ]),
  ing("guajillo", "Dried guajillo chiles", "guajillo chiles",
    ["guajillo", "guajillos", "guajillo chile", "guajillo chiles", "guajillo peppers"],
    ["Mexican"], "Spice & Seasoning", [...LATIN, ...INTL], b("Dried guajillo chiles", "International", 3.99), [
      s("Dried California / New Mexico chiles", "dried California or New Mexico chiles", 88, [...INTL, ...LATIN], [b("Dried New Mexico chiles", "International", 3.49)],
        "1:1 by count", "Similar mild heat and bright, tangy red-fruit flavor."),
      s("Ancho chili powder + sweet paprika", "ancho chili powder and paprika", 66, M,
        [b("Ancho chili powder (McCormick)", "Spices", 4.29), b("Sweet paprika", "Spices", 2.99)],
        "1 tbsp ancho powder + 1 tsp paprika per 3 chiles", "Close on color and earthiness; blend with a little stock to mimic the purée."),
    ]),
  ing("ancho", "Dried ancho chiles", "ancho chiles",
    ["ancho", "anchos", "ancho chile", "ancho chiles", "ancho chili"],
    ["Mexican"], "Spice & Seasoning", [...LATIN, ...INTL], b("Dried ancho chiles", "International", 3.99), [
      s("Pure ancho chili powder", "ancho chili powder", 76, M, [b("Ancho chili powder (McCormick)", "Spices", 4.29)],
        "1 tbsp powder per chile", "The same pepper, already ground — toast briefly in oil to wake it up."),
    ]),
  ing("chile-mulato", "Dried mulato chiles", "mulato chiles",
    ["mulato", "mulatos", "mulato chile", "mulato chiles"],
    ["Mexican"], "Spice & Seasoning", LATSPEC, b("Dried mulato chiles", "International", 4.49), [
      s("Extra anchos + cocoa powder", "extra anchos (plus ½ tsp cocoa each)", 84, [...LATIN, ...INTL],
        [b("Dried ancho chiles", "International", 3.99), b("Unsweetened cocoa powder", "Baking", 3.49)],
        "1 ancho + ½ tsp cocoa per mulato", "Mulatos are sun-dried poblanos like anchos — just darker and more chocolatey."),
      s("Ancho powder + cocoa", "ancho chili powder and cocoa", 64, M,
        [b("Ancho chili powder (McCormick)", "Spices", 4.29), b("Unsweetened cocoa powder", "Baking", 3.49)],
        "1 tbsp ancho powder + ½ tsp cocoa per chile", "Gets you the dark, bittersweet base in a pinch."),
    ]),
  ing("chile-pasilla", "Dried pasilla chiles", "pasilla chiles",
    ["pasilla", "pasillas", "pasilla chile", "pasilla chiles", "chile negro"],
    ["Mexican"], "Spice & Seasoning", LATIN, b("Dried pasilla chiles", "International", 3.99), [
      s("Dried ancho chiles", "more anchos", 80, [...LATIN, ...INTL], [b("Dried ancho chiles", "International", 3.99)],
        "1:1", "Fruitier and a bit sweeter, but the same raisiny depth."),
      s("Ancho + chipotle powder", "ancho and chipotle powders", 62, M,
        [b("Ancho chili powder (McCormick)", "Spices", 4.29), b("Chipotle chili powder", "Spices", 4.29)],
        "2 tsp ancho + ¼ tsp chipotle per chile", "Adds the smoky bitterness pasillas bring."),
    ]),
  ing("mexican-chocolate", "Mexican chocolate (Abuelita / Ibarra)", "Mexican chocolate",
    ["mexican chocolate", "abuelita", "ibarra", "chocolate de mesa", "chocolate mexicano"],
    ["Mexican"], "Pantry", [...LATIN, ...INTL], b("Mexican chocolate tablets (Abuelita)", "International", 4.29), [
      s("Dark chocolate + cinnamon + sugar", "dark chocolate with cinnamon and a little sugar", 85, M,
        [b("Dark chocolate bar (70%)", "Baking", 3.49), b("Ground cinnamon", "Spices", 2.99)],
        "1 oz chocolate + ¼ tsp cinnamon + 1 tsp sugar per oz", "Mexican chocolate is just chocolate, sugar and canela — easy to rebuild."),
    ]),
  ing("mexican-oregano", "Mexican oregano", "Mexican oregano",
    ["mexican oregano", "oregano mexicano"],
    ["Mexican", "Salvadoran", "Guatemalan"], "Spice & Seasoning", [...LATIN, ...INTL], b("Mexican oregano", "International", 2.49), [
      s("Oregano + marjoram", "regular oregano with a pinch of marjoram", 80, M,
        [b("Dried oregano", "Spices", 2.49), b("Dried marjoram", "Spices", 3.29)],
        "¾ tsp oregano + ¼ tsp marjoram per tsp", "Mexican oregano is citrusy and grassy; marjoram softens Mediterranean oregano's minty edge."),
    ]),
  ing("canela", "Canela (Ceylon cinnamon)", "canela",
    ["canela", "ceylon cinnamon", "true cinnamon"],
    ["Mexican", "Cuban", "Sri Lankan"], "Spice & Seasoning", [...LATIN, ...NAT, ...INTL], b("Canela sticks", "International", 2.99), [
      s("Regular (cassia) cinnamon — use half", "regular cinnamon", 80, M, [b("Cinnamon sticks", "Spices", 3.49)],
        "½ the amount", "Cassia is stronger and spicier; halve it to match canela's gentle sweetness."),
    ]),
  ing("avocado-leaves", "Dried avocado leaves", "avocado leaves",
    ["avocado leaves", "avocado leaf", "hoja de aguacate", "hojas de aguacate"],
    ["Mexican"], "Spice & Seasoning", LATSPEC, b("Dried avocado leaves", "International", 2.99), [
      s("Bay leaf + pinch of anise seed", "bay leaves with a pinch of anise seed", 76, M,
        [b("Bay leaves", "Spices", 2.99), b("Anise seed", "Spices", 3.49)],
        "1 bay leaf + ⅛ tsp anise per 2 leaves", "Recreates the herbal, faintly licorice aroma."),
    ]),
  ing("achiote", "Achiote paste", "achiote paste",
    ["achiote", "achiote paste", "achiote seeds", "annatto", "ground annatto", "annatto paste", "recado rojo", "el yucateco"],
    ["Mexican", "Yucatecan", "Guatemalan"], "Sauce & Paste", [...LATIN, ...INTL], b("Achiote paste (El Yucateco)", "International", 2.99), [
      s("Paprika, oregano, cumin & vinegar paste", "paprika–oregano–cumin vinegar paste", 70, M,
        [b("Sweet paprika", "Spices", 2.99), b("Ground cumin", "Spices", 2.99), b("White vinegar", "Oils & Vinegars", 1.99)],
        "1 tbsp paprika + ½ tsp each oregano & cumin + 1 tbsp vinegar per 2 tbsp", "Matches the red color and the tangy, earthy marinade base."),
    ]),
  ing("masarepa", "Masarepa (P.A.N. precooked corn flour)", "masarepa",
    ["masarepa", "harina pan", "p.a.n.", "pan flour", "precooked corn meal", "harina precocida", "areparina"],
    ["Venezuelan", "Colombian"], "Grain & Flour", [...LATIN, ...INTL], b("P.A.N. white corn meal", "International", 3.99), [
      s("Masa harina (Maseca)", "masa harina", 64, M, [b("Masa harina (Maseca)", "International", 3.49)],
        "1:1 plus 2–3 tbsp extra water; rest dough 10 min", "A different corn process, so arepas come out denser and more tortilla-like — still delicious."),
    ]),
  ing("queso-llanero", "Queso llanero / queso de mano", "queso llanero",
    ["queso llanero", "queso de mano", "queso telita", "queso blanco duro", "queso costeño", "queso guayanés"],
    ["Venezuelan", "Colombian"], "Dairy", LATSPEC, b("Queso llanero", "Deli", 6.99), [
      s("Fresh mozzarella + crumbled feta", "fresh mozzarella mixed with a little feta", 82, M,
        [b("Fresh mozzarella", "Dairy", 4.99), b("Feta cheese", "Dairy", 3.99)],
        "3 parts mozzarella : 1 part feta", "Mozzarella brings the stretch, feta the salty tang of Venezuelan white cheese."),
    ]),
  ing("aji-amarillo", "Ají amarillo paste", "ají amarillo paste",
    ["aji amarillo", "ají amarillo", "aji amarillo paste", "yellow chili paste"],
    ["Peruvian"], "Sauce & Paste", [...LATIN, ...INTL], b("Ají amarillo paste", "International", 4.99), [
      s("Roasted yellow pepper + habanero + turmeric", "blended roasted yellow bell pepper with a little habanero", 76, M,
        [b("Yellow bell pepper", "Produce", 1.49), b("Habanero peppers", "Produce", 1.29), b("Ground turmeric", "Spices", 2.99)],
        "1 roasted yellow pepper + ½ habanero + pinch turmeric per ¼ cup", "Fruity heat and sunny color — the two things ají amarillo is loved for."),
    ]),
  ing("aji-panca", "Ají panca paste", "ají panca",
    ["aji panca", "ají panca", "panca paste"],
    ["Peruvian"], "Sauce & Paste", LATSPEC, b("Ají panca paste", "International", 4.99), [
      s("Rehydrated ancho chile paste", "blended rehydrated ancho chile", 78, [...LATIN, ...INTL], [b("Dried ancho chiles", "International", 3.99)],
        "Soak 2 anchos, blend with 2 tbsp water per ¼ cup", "Both are mild, fruity, smoky dried red chiles."),
      s("Ancho powder + smoked paprika + oil", "ancho powder, smoked paprika and oil", 62, M,
        [b("Ancho chili powder (McCormick)", "Spices", 4.29), b("Smoked paprika", "Spices", 3.49)],
        "1 tbsp ancho + ½ tsp smoked paprika + 1 tbsp oil", "Gets the berry-smoke vibe in a pinch."),
    ]),
  ing("sazon", "Sazón con culantro y achiote", "sazón",
    ["sazon", "sazón", "sazon goya", "sazón goya"],
    ["Puerto Rican", "Cuban", "Dominican"], "Spice & Seasoning", [...LATIN, ...INTL], b("Goya Sazón packets", "International", 2.29), [
      s("DIY sazón blend", "homemade sazón (garlic powder, cumin, coriander & turmeric)", 80, M,
        [b("Garlic powder", "Spices", 2.99), b("Ground coriander", "Spices", 2.99), b("Ground turmeric", "Spices", 2.99)],
        "Per packet: ½ tsp each garlic powder, cumin, coriander, turmeric + ¼ tsp salt", "Turmeric stands in for annatto's color; the rest is the classic blend."),
    ]),
  ing("farofa", "Farinha de mandioca (cassava flour)", "farinha de mandioca",
    ["farofa", "farinha", "farinha de mandioca", "manioc flour", "cassava meal", "yuca flour"],
    ["Brazilian"], "Grain & Flour", LATSPEC, b("Farinha de mandioca (Yoki)", "International", 4.99), [
      s("Cassava flour, toasted", "toasted cassava flour", 85, NAT, [b("Cassava flour (Bob's Red Mill)", "Baking", 7.99)],
        "1:1 — toast in butter until golden", "The same root in a finer grind; toast well for farofa's sandy crunch."),
      s("Panko toasted in butter", "panko toasted in butter", 64, M, [b("Panko breadcrumbs", "Baking", 2.99)],
        "1:1", "Not gluten-free, but delivers the buttery crunch over beans."),
    ]),
  ing("carne-seca", "Carne seca (Brazilian dried beef)", "carne seca",
    ["carne seca", "carne de sol", "charque", "jerked beef", "dried beef"],
    ["Brazilian"], "Protein", LATSPEC, b("Carne seca", "Meat & Seafood", 12.99), [
      s("Corned beef brisket", "corned beef brisket", 76, M, [b("Corned beef brisket", "Meat & Seafood", 11.99)],
        "1:1 by weight; rinse well", "Salt-cured beef with a similar dense, shreddable chew."),
    ]),
  ing("linguica", "Linguiça calabresa", "linguiça",
    ["linguica", "linguiça", "calabresa", "paio", "chouriço", "chourico", "portuguese sausage"],
    ["Brazilian", "Portuguese"], "Protein", LATSPEC, b("Linguiça calabresa", "Meat & Seafood", 7.99), [
      s("Smoked kielbasa", "smoked kielbasa", 82, M, [b("Smoked kielbasa", "Meat & Seafood", 5.49)],
        "1:1", "Garlicky smoked pork sausage — very close to calabresa."),
      s("Andouille sausage", "andouille sausage", 80, M, [b("Andouille sausage", "Meat & Seafood", 6.49)],
        "1:1", "Spicier and smokier — great in feijoada."),
    ]),
];
