import type { SpecialtyIngredient } from "@/lib/types";
import { ASIAN, EURO, INDIAN, INTL, LATIN, M, MIDEAST, NAT, b, ing, s } from "./helpers";

/** East & Southeast Asian, South Asian, Middle Eastern and European specialty ingredients. */
export const ASIA_MIDEAST_EUROPE: SpecialtyIngredient[] = [
  /* ---------------- Southeast Asia ---------------- */
  ing("thai-basil", "Thai basil (húng quế)", "Thai basil",
    ["thai basil", "hung que", "húng quế", "horapha", "holy basil", "bai krapao", "krapao"],
    ["Thai", "Vietnamese", "Lao"], "Fresh Herb", ASIAN, b("Thai basil", "Produce", 2.49), [
      s("Sweet basil + a few mint leaves", "Italian basil with a few mint leaves", 80, M,
        [b("Fresh basil", "Produce", 2.99), b("Fresh mint", "Produce", 2.49)],
        "4 basil leaves : 1 mint leaf", "Mint adds back the cool, anise-like bite Italian basil lacks."),
    ]),
  ing("rock-sugar", "Yellow rock sugar", "rock sugar",
    ["rock sugar", "yellow rock sugar", "lump sugar", "duong phen", "đường phèn", "bing tang"],
    ["Vietnamese", "Chinese"], "Pantry", ASIAN, b("Yellow rock sugar", "International", 3.49), [
      s("Turbinado sugar", "turbinado sugar", 92, M, [b("Turbinado sugar (Sugar in the Raw)", "Baking", 3.99)],
        "1:1 by weight (start with ¾)", "Mild, clean sweetness that keeps the broth crystal clear."),
    ]),
  ing("black-cardamom", "Black cardamom pods", "black cardamom",
    ["black cardamom", "thao qua", "thảo quả", "badi elaichi", "kali elaichi", "tsaoko"],
    ["Vietnamese", "Indian", "Chinese"], "Spice & Seasoning", [...INDIAN, ...ASIAN], b("Black cardamom pods", "International", 4.99), [
      s("Green cardamom + smoked paprika", "green cardamom pods with a pinch of smoked paprika", 76, M,
        [b("Green cardamom pods", "Spices", 6.99), b("Smoked paprika", "Spices", 3.49)],
        "2 green pods + pinch smoked paprika per black pod", "Black cardamom is smoke-dried — paprika supplies that campfire note."),
    ]),
  ing("fish-sauce", "Fish sauce", "fish sauce",
    ["fish sauce", "nuoc mam", "nước mắm", "nam pla", "patis"],
    ["Vietnamese", "Thai", "Filipino", "Lao"], "Sauce & Paste", [...INTL, ...ASIAN, ...NAT], b("Fish sauce (Red Boat / Three Crabs)", "International", 4.99), [
      s("Soy sauce + anchovy paste + lime", "soy sauce with anchovy paste and lime", 74, M,
        [b("Soy sauce", "International", 2.99), b("Anchovy paste (tube)", "Canned Goods", 3.29)],
        "1 tbsp soy + ½ tsp anchovy paste + squeeze of lime per tbsp", "Anchovy brings the fermented-fish depth; soy brings the salt."),
    ]),
  ing("rice-noodles", "Bánh phở / flat rice noodles", "rice noodles",
    ["banh pho", "bánh phở", "pho noodles", "rice sticks", "rice noodles", "flat rice noodles", "rice stick noodles", "sen lek", "kway teow"],
    ["Vietnamese", "Thai"], "Grain & Flour", ASIAN, b("Fresh bánh phở noodles", "Refrigerated", 3.99), [
      s("Thai Kitchen stir-fry rice noodles", "dried flat rice noodles", 90, [...INTL, ...NAT],
        [b("Thai Kitchen stir-fry rice noodles", "International", 3.29)],
        "1:1", "The same rice-and-water noodle, just dried — soak instead of blanching."),
      s("Linguine", "linguine", 55, M, [b("Linguine", "Pasta", 1.49)],
        "Cook al dente and rinse well", "Wheat changes the texture, but it slurps just fine in a pinch."),
    ]),
  ing("makrut-lime", "Makrut (kaffir) lime leaves", "makrut lime leaves",
    ["makrut", "kaffir lime leaves", "kaffir lime leaf", "lime leaves", "makrut lime leaves", "bai makrut", "daun jeruk"],
    ["Thai", "Indonesian", "Malaysian", "Lao", "Cambodian"], "Fresh Herb", ASIAN, b("Makrut lime leaves", "Produce", 2.99), [
      s("Lime zest + bay leaf", "lime zest and a bay leaf", 76, M, [b("Limes", "Produce", 1.99), b("Bay leaves", "Spices", 2.99)],
        "Zest of 1 lime + 1 bay leaf per 4 leaves", "Zest gives the floral citrus, bay the leafy, resinous backbone."),
    ]),
  ing("galangal", "Galangal root", "galangal",
    ["galangal", "kha", "lengkuas", "laos root", "blue ginger", "thai ginger"],
    ["Thai", "Indonesian", "Malaysian"], "Produce", ASIAN, b("Fresh galangal", "Produce", 3.49), [
      s("Fresh ginger + lemon", "sliced ginger plus a squeeze of lemon", 72, M,
        [b("Fresh ginger root", "Produce", 1.29), b("Lemon", "Produce", 0.79)],
        "1:1 plus ½ tsp lemon juice per inch", "Galangal is piney and citrusy where ginger is spicy — lemon closes the gap."),
    ]),
  ing("lemongrass", "Fresh lemongrass", "lemongrass",
    ["lemongrass", "lemon grass", "takrai", "sereh"],
    ["Thai", "Vietnamese", "Indonesian"], "Fresh Herb", [...ASIAN, ...NAT, ...INTL], b("Fresh lemongrass stalks", "Produce", 2.49), [
      s("Lemongrass paste (Gourmet Garden)", "lemongrass paste", 88, M, [b("Gourmet Garden lemongrass paste", "Produce", 4.49)],
        "1 tbsp paste per stalk", "Real lemongrass, just pre-ground and stored in a tube."),
    ]),
  ing("palm-sugar", "Palm sugar", "palm sugar",
    ["palm sugar", "nam tan pip", "gula melaka", "gula jawa", "coconut palm sugar"],
    ["Thai", "Indonesian", "Malaysian"], "Pantry", ASIAN, b("Palm sugar", "International", 3.99), [
      s("Coconut sugar", "coconut sugar", 90, M, [b("Coconut sugar", "Baking", 5.49)],
        "1:1", "Made from coconut palm sap — the same caramel, butterscotch flavor."),
      s("Dark brown sugar", "dark brown sugar", 82, M, [b("Dark brown sugar", "Baking", 2.49)],
        "1:1, packed", "Molasses notes mimic palm sugar's caramel depth."),
    ]),
  ing("tamarind", "Tamarind paste", "tamarind paste",
    ["tamarind", "tamarind paste", "tamarind concentrate", "tamarind pulp", "imli", "asam jawa", "tamarindo"],
    ["Thai", "Indian", "Indonesian", "Mexican"], "Sauce & Paste", [...ASIAN, ...INDIAN, ...LATIN, ...INTL], b("Tamarind concentrate", "International", 3.49), [
      s("Lime juice + brown sugar + Worcestershire", "lime juice, brown sugar and a dash of Worcestershire", 74, M,
        [b("Limes", "Produce", 1.99), b("Worcestershire sauce", "Condiments", 2.99)],
        "1 tbsp lime + 1 tsp brown sugar + ½ tsp Worcestershire per tbsp", "Worcestershire actually contains tamarind — the trio recreates its sweet-sour fruitiness."),
    ]),
  ing("thai-chili", "Thai bird's eye chilies", "Thai chilies",
    ["thai chili", "thai chilies", "thai chile", "bird's eye chili", "birds eye chili", "prik kee noo", "siling labuyo", "cabe rawit"],
    ["Thai", "Vietnamese", "Filipino", "Indonesian"], "Produce", [...ASIAN, ...NAT], b("Thai bird's eye chilies", "Produce", 2.49), [
      s("Serrano peppers", "serrano peppers", 80, M, [b("Serrano peppers", "Produce", 0.99)],
        "1 serrano per 2–3 Thai chilies", "Clean, bright heat — slice thin and keep the seeds for extra kick."),
    ]),
  ing("thai-eggplant", "Thai eggplant", "Thai eggplant",
    ["thai eggplant", "makhuea pro", "pea eggplant", "green eggplant"],
    ["Thai", "Lao"], "Produce", ASIAN, b("Thai eggplant", "Produce", 3.49), [
      s("Italian eggplant or zucchini", "eggplant or zucchini chunks", 72, M, [b("Eggplant", "Produce", 1.99)],
        "1:1 by weight in 1-inch chunks; add 5 min later", "Soaks up curry just as well — add later so it doesn't turn mushy."),
    ]),
  ing("shrimp-paste", "Shrimp paste (kapi / terasi / bagoong)", "shrimp paste",
    ["shrimp paste", "kapi", "terasi", "belacan", "bagoong", "mam tom", "mắm tôm"],
    ["Thai", "Indonesian", "Malaysian", "Filipino", "Vietnamese"], "Sauce & Paste", ASIAN, b("Shrimp paste", "International", 3.99), [
      s("Anchovy paste + fish sauce", "anchovy paste with a splash of fish sauce", 75, INTL,
        [b("Anchovy paste (tube)", "Canned Goods", 3.29), b("Fish sauce", "International", 3.49)],
        "1 tsp anchovy paste + ½ tsp fish sauce per tsp", "Concentrated, fermented seafood funk with a similar salty punch."),
      s("Anchovy paste", "anchovy paste", 66, M, [b("Anchovy paste (tube)", "Canned Goods", 3.29)],
        "1:1", "Brings the pungent depth on its own."),
    ]),
  ing("dried-shrimp", "Dried shrimp", "dried shrimp",
    ["dried shrimp", "hae bee", "camaron seco", "camarones secos", "xia mi"],
    ["Thai", "Chinese", "Vietnamese", "Mexican"], "Protein", [...ASIAN, ...LATIN], b("Dried shrimp", "International", 5.99), [
      s("Minced seared shrimp + fish sauce", "minced, hard-seared shrimp with a dash of fish sauce", 64, M,
        [b("Small peeled shrimp (frozen)", "Frozen", 7.99)],
        "¼ cup minced shrimp + ½ tsp fish sauce per 2 tbsp dried", "Sear hard to concentrate the flavor; fish sauce adds the dried-shrimp funk."),
    ]),
  ing("kecap-manis", "Kecap manis (sweet soy sauce)", "kecap manis",
    ["kecap manis", "ketjap manis", "sweet soy sauce", "sweet soy"],
    ["Indonesian", "Malaysian"], "Sauce & Paste", ASIAN, b("Kecap manis (ABC)", "International", 3.99), [
      s("Soy sauce + brown sugar, simmered", "soy sauce simmered with brown sugar until syrupy", 88, M,
        [b("Soy sauce", "International", 2.99), b("Dark brown sugar", "Baking", 2.49)],
        "Simmer ½ cup soy + ½ cup brown sugar 3–4 min", "That's exactly how kecap manis is made — soy thickened with palm sugar."),
    ]),
  ing("garlic-chives", "Garlic chives (Chinese chives)", "garlic chives",
    ["garlic chives", "chinese chives", "gau choy", "buchu", "nira"],
    ["Chinese", "Korean", "Thai", "Vietnamese"], "Fresh Herb", ASIAN, b("Garlic chives", "Produce", 2.49), [
      s("Scallions + minced garlic", "scallions with a little minced garlic", 78, M,
        [b("Scallions (green onions)", "Produce", 0.99), b("Garlic", "Produce", 0.69)],
        "1 bunch scallions + 1 garlic clove per bunch", "Scallions give the green, oniony crunch; garlic the 'chive' bite."),
    ]),
  ing("calamansi", "Calamansi", "calamansi juice",
    ["calamansi", "kalamansi", "calamondin", "philippine lime"],
    ["Filipino"], "Produce", ASIAN, b("Calamansi (or frozen juice)", "Produce", 3.99), [
      s("Lime juice + splash of orange juice", "lime juice with a splash of orange juice", 85, M,
        [b("Limes", "Produce", 1.99), b("Orange", "Produce", 0.99)],
        "3 parts lime : 1 part orange", "Calamansi tastes like a cross between lime and mandarin — so blend them."),
    ]),
  ing("sinigang-mix", "Tamarind soup base (sinigang mix)", "sinigang tamarind base",
    ["sinigang mix", "sinigang sa sampalok", "knorr sinigang", "sinigang base", "sampalok"],
    ["Filipino"], "Spice & Seasoning", ASIAN, b("Knorr Sinigang sa Sampalok mix", "International", 1.99), [
      s("Tamarind concentrate + fish sauce", "tamarind concentrate with fish sauce", 88, [...INTL, ...LATIN, ...INDIAN],
        [b("Tamarind concentrate", "International", 3.49), b("Fish sauce", "International", 3.49)],
        "2 tbsp tamarind + 1 tbsp fish sauce per packet", "The packet is mostly tamarind and salt — this is the from-scratch version."),
      s("Lemon & lime juice", "fresh lemon and lime juice", 70, M, [b("Lemons", "Produce", 0.79), b("Limes", "Produce", 1.99)],
        "¼ cup mixed juice + 1 tbsp fish sauce (or 1 tsp salt) per packet, added off heat", "Brings the signature sourness; add it last so it stays bright."),
    ]),
  ing("kangkong", "Kangkong (water spinach)", "kangkong",
    ["kangkong", "water spinach", "ong choy", "rau muong", "morning glory", "pak boong"],
    ["Filipino", "Vietnamese", "Thai", "Chinese"], "Produce", ASIAN, b("Kangkong (water spinach)", "Produce", 2.99), [
      s("Baby bok choy", "baby bok choy", 78, M, [b("Baby bok choy", "Produce", 2.49)],
        "1:1, halved lengthwise", "Keeps a crisp stem and tender leaf like kangkong."),
      s("Fresh spinach", "spinach", 74, M, [b("Fresh spinach", "Produce", 3.49)],
        "1:1 — add in the last minute", "Wilts the same way, minus the hollow crunchy stems."),
    ]),
  ing("taro", "Taro root (gabi)", "taro",
    ["taro", "gabi", "dasheen", "eddo", "malanga", "yautia", "arbi", "kalo"],
    ["Filipino", "Chinese", "Caribbean", "Hawaiian"], "Produce", [...ASIAN, ...LATIN, "african_caribbean"], b("Taro root", "Produce", 2.99), [
      s("Yukon Gold potatoes", "Yukon Gold potatoes", 74, M, [b("Yukon Gold potatoes", "Produce", 3.99)],
        "1:1 by weight", "Creamy and starchy enough to thicken the broth like gabi does."),
    ]),
  ing("long-beans", "Long beans (sitaw)", "long beans",
    ["long beans", "sitaw", "yardlong beans", "snake beans"],
    ["Filipino", "Chinese", "Thai", "Vietnamese"], "Produce", ASIAN, b("Long beans", "Produce", 2.99), [
      s("Green beans", "green beans", 90, M, [b("Fresh green beans", "Produce", 2.49)],
        "1:1, cut into 2-inch pieces", "Same family, same snap — just shorter and sweeter."),
    ]),
  ing("daikon", "Daikon radish", "daikon",
    ["daikon", "labanos", "korean radish", "lo bok", "white radish", "mooli"],
    ["Filipino", "Korean", "Japanese", "Chinese", "Vietnamese"], "Produce", [...ASIAN, ...NAT, ...INTL], b("Daikon radish", "Produce", 1.99), [
      s("Turnips", "turnips", 74, M, [b("Turnips", "Produce", 1.49)],
        "1:1 by weight", "A mild, slightly peppery root that softens the same way in soup."),
    ]),
  ing("cane-vinegar", "Cane vinegar (sukang Iloko)", "cane vinegar",
    ["cane vinegar", "sukang iloko", "datu puti", "sukang maasim", "coconut vinegar", "palm vinegar"],
    ["Filipino"], "Sauce & Paste", ASIAN, b("Datu Puti cane vinegar", "International", 2.49), [
      s("Rice vinegar", "rice vinegar", 88, [...INTL, ...NAT], [b("Rice vinegar (unseasoned)", "International", 2.79)],
        "1:1", "Mild and clean — the closest match to Filipino cane vinegar."),
      s("Apple cider vinegar", "apple cider vinegar", 80, M, [b("Apple cider vinegar", "Oils & Vinegars", 2.49)],
        "1:1", "A touch fruitier with the same gentle acidity."),
    ]),

  /* ---------------- East Asia ---------------- */
  ing("gochugaru", "Gochugaru (Korean chili flakes)", "gochugaru",
    ["gochugaru", "korean chili flakes", "korean red pepper flakes", "korean chili powder", "korean red pepper powder", "kochukaru"],
    ["Korean"], "Spice & Seasoning", ASIAN, b("Gochugaru", "International", 7.99), [
      s("Aleppo pepper", "Aleppo pepper", 86, [...NAT, ...MIDEAST], [b("Aleppo pepper", "Spices", 6.99)],
        "1:1", "Fruity, moderately hot and oily-flaked — remarkably close to gochugaru."),
      s("Sweet paprika + cayenne", "sweet paprika with a little cayenne", 76, M,
        [b("Sweet paprika", "Spices", 2.99), b("Ground cayenne pepper", "Spices", 2.49)],
        "2 tsp paprika + ¼ tsp cayenne per tbsp", "Paprika supplies the color and sweetness, cayenne the gentle heat."),
    ]),
  ing("gochujang", "Gochujang (Korean chili paste)", "gochujang",
    ["gochujang", "korean chili paste", "kochujang", "korean red pepper paste"],
    ["Korean"], "Sauce & Paste", [...ASIAN, ...INTL, ...NAT], b("Gochujang", "International", 5.99), [
      s("Sriracha + miso + honey", "sriracha mixed with miso and honey", 76, [...INTL, ...NAT],
        [b("Sriracha", "International", 3.49), b("Miso paste", "International", 5.49)],
        "1 tbsp sriracha + 1 tbsp miso + 1 tsp honey per 2 tbsp", "Miso supplies the fermented soybean depth, sriracha the heat, honey the sweetness."),
      s("Sriracha + tomato paste + soy", "sriracha with tomato paste and soy sauce", 60, M,
        [b("Sriracha", "International", 3.49), b("Tomato paste", "Canned Goods", 1.29)],
        "1 tbsp sriracha + 1 tbsp tomato paste + 1 tsp soy per 2 tbsp", "Thick, spicy and savory — not fermented, but it works."),
    ]),
  ing("kimchi", "Aged napa cabbage kimchi", "kimchi",
    ["kimchi", "aged kimchi", "sour kimchi", "kimchee", "cabbage kimchi", "mukeunji"],
    ["Korean"], "Produce", [...ASIAN, ...NAT, ...INTL], b("Napa cabbage kimchi", "Refrigerated", 6.99), [
      s("Sauerkraut + chili + garlic", "quick 'kimchi' of sauerkraut, chili flakes & garlic", 66, M,
        [b("Refrigerated sauerkraut", "Refrigerated", 3.99), b("Crushed red pepper flakes", "Spices", 2.49)],
        "1:1; per cup add 1 tbsp chili flakes + 1 garlic clove", "Already fermented and sour — chili and garlic push it toward kimchi."),
    ]),
  ing("short-grain-rice", "Korean short-grain rice", "short-grain rice",
    ["short grain rice", "short-grain rice", "korean rice", "calrose rice", "japanese rice"],
    ["Korean", "Japanese"], "Grain & Flour", ASIAN, b("Korean short-grain rice", "Rice & Grains", 8.99), [
      s("Sushi rice (Nishiki / Botan)", "sushi rice", 95, [...INTL, ...NAT], [b("Nishiki sushi rice", "International", 6.99)],
        "1:1", "The same medium/short-grain japonica rice Korean homes use."),
      s("Arborio rice", "arborio rice", 70, M, [b("Arborio rice", "Rice & Grains", 3.99)],
        "1:1 — rinse very well", "Sticky and plump; rinse well to wash off extra starch."),
    ]),
  ing("anchovy-stock", "Dried anchovy & kelp (dashima) stock", "anchovy-kelp stock",
    ["anchovy stock", "myeolchi", "dashima", "anchovy broth", "kelp stock", "myeolchi yuksu"],
    ["Korean"], "Pantry", ASIAN, b("Dried soup anchovies & dashima", "International", 8.99), [
      s("Chicken broth + fish sauce", "chicken broth with a splash of fish sauce", 74, INTL,
        [b("Low-sodium chicken broth", "Soups & Broths", 2.99), b("Fish sauce", "International", 3.49)],
        "2 cups broth + 1 tsp fish sauce", "A rich base plus fermented fish for that deep-sea savoriness."),
      s("Chicken broth + anchovy paste", "chicken broth with a little anchovy paste", 70, M,
        [b("Low-sodium chicken broth", "Soups & Broths", 2.99), b("Anchovy paste (tube)", "Canned Goods", 3.29)],
        "2 cups broth + ½ tsp anchovy paste", "Same idea — anchovy in a different form."),
    ]),
  ing("doubanjiang", "Doubanjiang (chili bean paste)", "doubanjiang",
    ["doubanjiang", "toban djan", "toban jan", "chili bean paste", "broad bean paste", "pixian"],
    ["Chinese", "Sichuan"], "Sauce & Paste", ASIAN, b("Pixian doubanjiang", "International", 4.99), [
      s("Miso + chili garlic sauce", "miso blended with chili garlic sauce", 78, [...INTL, ...NAT],
        [b("Miso paste", "International", 5.49), b("Chili garlic sauce (Huy Fong)", "International", 3.29)],
        "1 tbsp miso + 1 tbsp chili garlic sauce per 2 tbsp", "Fermented bean funk + chili heat = the soul of doubanjiang."),
      s("Chili garlic sauce + soy sauce", "chili garlic sauce with soy sauce", 60, M,
        [b("Chili garlic sauce (Huy Fong)", "International", 3.29)],
        "1½ tbsp chili sauce + 1 tsp soy per 2 tbsp", "Spicy and salty; add a pinch of sugar for depth."),
    ]),
  ing("sichuan-peppercorn", "Sichuan peppercorns", "Sichuan peppercorns",
    ["sichuan peppercorn", "sichuan peppercorns", "szechuan peppercorn", "szechuan pepper", "hua jiao", "huajiao"],
    ["Chinese", "Sichuan"], "Spice & Seasoning", [...ASIAN, ...NAT], b("Sichuan peppercorns", "International", 5.99), [
      s("Black pepper + coriander + lemon zest", "black pepper and coriander seed (plus lemon zest at the end)", 55, M,
        [b("Whole black peppercorns", "Spices", 3.99), b("Coriander seed", "Spices", 2.99), b("Lemon", "Produce", 0.79)],
        "½ tsp each pepper & coriander + pinch zest per tsp", "Captures the citrusy aroma — but nothing replicates the tingly numbness."),
    ]),
  ing("douchi", "Fermented black beans (douchi)", "fermented black beans",
    ["fermented black beans", "douchi", "dou chi", "salted black beans", "chinese black beans", "tausi"],
    ["Chinese", "Filipino"], "Sauce & Paste", ASIAN, b("Fermented black beans", "International", 2.99), [
      s("Black bean garlic sauce", "black bean garlic sauce", 85, INTL, [b("Lee Kum Kee black bean garlic sauce", "International", 3.49)],
        "1 tbsp sauce per tbsp beans; reduce salt", "Made from the very same fermented black beans."),
      s("Soy sauce + a drop of molasses", "soy sauce with a drop of molasses", 54, M, [b("Molasses", "Baking", 3.99)],
        "2 tsp soy + ¼ tsp molasses per tbsp", "Salty, dark and savory — a last resort."),
    ]),
  ing("shaoxing", "Shaoxing rice wine", "Shaoxing wine",
    ["shaoxing", "shaoxing wine", "shao hsing", "chinese cooking wine", "huangjiu", "mijiu"],
    ["Chinese"], "Sauce & Paste", ASIAN, b("Shaoxing cooking wine", "International", 3.99), [
      s("Dry sherry", "dry sherry", 90, M, [b("Dry sherry", "Wine & Cooking Wine", 6.99)],
        "1:1", "The chef's go-to: nutty, oxidized and slightly sweet like Shaoxing."),
    ]),
  ing("chili-crisp", "Chinese chili crisp (Lao Gan Ma)", "chili crisp",
    ["chili crisp", "chili oil", "lao gan ma", "chili crunch", "la you", "hong you"],
    ["Chinese", "Sichuan"], "Sauce & Paste", [...ASIAN, ...INTL, ...NAT], b("Lao Gan Ma spicy chili crisp", "International", 4.99), [
      s("DIY chili oil", "homemade chili oil (pepper flakes & garlic bloomed in hot oil)", 76, M,
        [b("Crushed red pepper flakes", "Spices", 2.49), b("Vegetable oil", "Oils & Vinegars", 3.99)],
        "Pour ½ cup smoking-hot oil over 3 tbsp flakes + 2 minced garlic cloves", "Two minutes for the same toasty, crunchy heat."),
    ]),
  ing("dashi", "Dashi stock", "dashi",
    ["dashi", "hondashi", "bonito stock", "kombu dashi", "awase dashi"],
    ["Japanese"], "Pantry", ASIAN, b("Hondashi granules", "International", 4.99), [
      s("Chicken broth + soy + fish sauce", "chicken broth seasoned with soy & fish sauce", 70, INTL,
        [b("Low-sodium chicken broth", "Soups & Broths", 2.99), b("Fish sauce", "International", 3.49)],
        "1 cup broth + ½ tsp soy + ¼ tsp fish sauce", "Savory and light with a hint of the sea."),
      s("Vegetable broth steeped with nori", "vegetable broth steeped with nori", 64, M,
        [b("Low-sodium vegetable broth", "Soups & Broths", 2.99), b("Roasted seaweed snacks", "Snacks", 1.99)],
        "Steep 1 nori sheet in 2 cups hot broth for 10 min", "Nori brings the oceanic umami of kombu."),
    ]),
  ing("bonito", "Katsuobushi (bonito flakes)", "bonito flakes",
    ["katsuobushi", "bonito flakes", "bonito", "dried bonito"],
    ["Japanese"], "Protein", [...ASIAN, ...NAT], b("Katsuobushi", "International", 5.99), [
      s("Furikake", "furikake", 70, INTL, [b("Furikake rice seasoning", "International", 3.99)],
        "Sprinkle to taste", "Many furikakes contain bonito — smoky, savory and oceanic."),
      s("Crumbled nori + smoked paprika", "crumbled nori with a pinch of smoked paprika", 56, M,
        [b("Roasted seaweed snacks", "Snacks", 1.99), b("Smoked paprika", "Spices", 3.49)],
        "Sprinkle to taste", "Seaweed plus smoke mimics the flavor of the dancing flakes."),
    ]),
  ing("okonomi-sauce", "Okonomiyaki sauce (Otafuku)", "okonomiyaki sauce",
    ["okonomi sauce", "okonomiyaki sauce", "otafuku", "tonkatsu sauce", "bulldog sauce"],
    ["Japanese"], "Sauce & Paste", ASIAN, b("Otafuku okonomi sauce", "International", 5.49), [
      s("Ketchup + Worcestershire + soy + honey", "homemade okonomi sauce (ketchup, Worcestershire, soy & honey)", 86, M,
        [b("Ketchup", "Condiments", 2.49), b("Worcestershire sauce", "Condiments", 2.99), b("Honey", "Baking", 4.99)],
        "3 tbsp ketchup + 1 tbsp Worcestershire + 1 tsp soy + 1 tsp honey", "Fruity, tangy and savory-sweet — basically what's in the bottle."),
    ]),
  ing("kewpie", "Kewpie mayonnaise", "Kewpie mayo",
    ["kewpie", "kewpie mayo", "japanese mayo", "japanese mayonnaise"],
    ["Japanese"], "Sauce & Paste", [...ASIAN, ...INTL, ...NAT], b("Kewpie mayonnaise", "International", 5.99), [
      s("Mayo + rice vinegar + pinch of sugar", "mayonnaise with a little rice vinegar and sugar", 85, M, [b("Mayonnaise", "Condiments", 3.99)],
        "¼ cup mayo + ½ tsp rice vinegar + ¼ tsp sugar (+ pinch of MSG)", "Kewpie uses only yolks, rice vinegar and MSG — this gets you close."),
    ]),
  ing("aonori", "Aonori (green laver flakes)", "aonori",
    ["aonori", "ao nori", "green laver", "seaweed flakes"],
    ["Japanese"], "Spice & Seasoning", ASIAN, b("Aonori flakes", "International", 3.99), [
      s("Roasted seaweed snacks, crumbled", "crumbled roasted seaweed", 76, M, [b("Roasted seaweed snacks", "Snacks", 1.99)],
        "1 sheet crumbled ≈ 1 tsp aonori", "The same seaweed family — crumble finely and sprinkle."),
    ]),
  ing("beni-shoga", "Beni shoga (red pickled ginger)", "beni shoga",
    ["beni shoga", "benishoga", "red pickled ginger", "pickled red ginger"],
    ["Japanese"], "Produce", ASIAN, b("Beni shoga", "Refrigerated", 3.49), [
      s("Sushi ginger (gari), chopped", "chopped sushi ginger", 80, [...INTL, ...NAT], [b("Pickled sushi ginger", "International", 3.29)],
        "1:1", "Sweeter and paler, but the same sharp pickled-ginger zing."),
      s("Quick-pickled fresh ginger", "fresh ginger quick-pickled in vinegar", 64, M, [b("Fresh ginger root", "Produce", 1.29)],
        "Julienne 1 inch ginger; soak 15 min in 2 tbsp vinegar + pinch of salt", "Fast and sharp."),
    ]),
  ing("nagaimo", "Nagaimo (mountain yam)", "grated nagaimo",
    ["nagaimo", "yamaimo", "mountain yam", "chinese yam"],
    ["Japanese"], "Produce", ASIAN, b("Nagaimo", "Produce", 4.99), [
      s("Extra egg + cornstarch", "1 extra egg + 1 tbsp cornstarch", 75, M,
        [b("Eggs (dozen)", "Dairy", 3.49), b("Cornstarch", "Baking", 1.99)],
        "1 egg + 1 tbsp cornstarch per ¼ cup grated nagaimo", "Nagaimo adds fluffiness and binding — egg and starch do the same job."),
    ]),
  ing("okonomiyaki-flour", "Okonomiyaki flour", "okonomiyaki flour",
    ["okonomiyaki flour", "okonomiyaki mix", "okonomiyaki ko"],
    ["Japanese"], "Grain & Flour", ASIAN, b("Otafuku okonomiyaki flour", "International", 4.99), [
      s("All-purpose flour + baking powder", "all-purpose flour with a little baking powder", 82, M,
        [b("All-purpose flour", "Baking", 2.99), b("Baking powder", "Baking", 2.49)],
        "1 cup flour + ½ tsp baking powder", "The mix is mostly wheat flour, leavening and dashi powder."),
    ]),

  /* ---------------- South Asia ---------------- */
  ing("curry-leaves", "Fresh curry leaves", "curry leaves",
    ["curry leaves", "curry leaf", "kadi patta", "kari patta", "karuveppilai", "kariveppila"],
    ["Indian", "Sri Lankan", "Malaysian"], "Fresh Herb", INDIAN, b("Fresh curry leaves", "Produce", 1.99), [
      s("Lime zest + bay leaf + basil", "lime zest with a bay leaf and a few basil leaves", 56, M,
        [b("Limes", "Produce", 1.99), b("Bay leaves", "Spices", 2.99), b("Fresh basil", "Produce", 2.99)],
        "Zest of ½ lime + 1 bay leaf + 3 basil leaves per sprig", "Honestly, nothing fully replaces curry leaves — this mimics the citrusy-herbal note. Never use curry powder instead."),
    ]),
  ing("asafoetida", "Asafoetida (hing)", "asafoetida",
    ["asafoetida", "hing", "heeng", "asafetida"],
    ["Indian"], "Spice & Seasoning", [...INDIAN, ...NAT], b("Asafoetida (hing) powder", "Spices", 4.99), [
      s("Garlic powder + onion powder", "garlic powder and onion powder", 72, M,
        [b("Garlic powder", "Spices", 2.99), b("Onion powder", "Spices", 2.99)],
        "¼ tsp each per pinch of hing", "Bloomed in oil, hing tastes like mellow cooked garlic and leeks."),
    ]),
  ing("kasuri-methi", "Kasuri methi (dried fenugreek leaves)", "kasuri methi",
    ["kasuri methi", "kasoori methi", "dried fenugreek leaves", "fenugreek leaves", "methi leaves", "shanbalileh"],
    ["Indian", "Persian", "Pakistani"], "Fresh Herb", [...INDIAN, ...MIDEAST], b("Kasuri methi", "International", 3.49), [
      s("Ground fenugreek seed", "a pinch of ground fenugreek", 72, [...NAT, ...INTL], [b("Ground fenugreek", "Spices", 4.49)],
        "⅛ tsp ground seed per tbsp leaves", "The same plant — the seed is stronger and more bitter, so go light."),
      s("Celery leaves + a drop of maple syrup", "chopped celery leaves with a drop of maple syrup", 60, M,
        [b("Celery with leaves", "Produce", 1.99), b("Maple syrup", "Breakfast", 5.99)],
        "1 tbsp chopped leaves + 2 drops maple per tbsp", "Fenugreek and maple share the same aroma compound (sotolon); celery adds the green bitterness."),
    ]),
  ing("paneer", "Paneer", "paneer",
    ["paneer", "panir", "indian cottage cheese"],
    ["Indian", "Pakistani"], "Dairy", [...INDIAN, ...NAT], b("Paneer block", "Dairy", 5.99), [
      s("Queso blanco (frying cheese)", "queso blanco", 86, M, [b("Queso blanco / queso para freír", "Dairy", 4.49)],
        "1:1, cubed", "A fresh, mild, non-melting cheese made almost exactly like paneer."),
      s("Halloumi", "halloumi", 80, [...NAT, ...MIDEAST, ...INTL], [b("Halloumi", "Dairy", 6.99)],
        "1:1; soak cubes 10 min to tame the salt", "Holds its shape and sears beautifully — just saltier."),
      s("Extra-firm tofu", "extra-firm tofu", 64, M, [b("Extra-firm tofu", "Refrigerated", 2.49)],
        "1:1, pressed 15 min", "Dairy-free and soaks up the gravy well."),
    ]),
  ing("ghee", "Ghee", "ghee",
    ["ghee", "clarified butter", "desi ghee"],
    ["Indian", "Pakistani", "Jordanian"], "Dairy", [...INDIAN, ...NAT, ...INTL], b("Ghee", "International", 7.99), [
      s("Clarified butter", "clarified butter", 95, M, [b("Unsalted butter", "Dairy", 4.49)],
        "Melt 1¼ cups butter, skim, pour off the clear fat for 1 cup ghee", "Ghee is simply butter cooked until the milk solids toast."),
    ]),
  ing("kewra", "Kewra water", "kewra water",
    ["kewra", "kewra water", "keora"],
    ["Indian", "Pakistani", "Bangladeshi"], "Pantry", [...INDIAN, ...MIDEAST], b("Kewra water", "International", 3.49), [
      s("Rose water", "rose water", 74, [...MIDEAST, ...NAT, ...INTL], [b("Rose water", "International", 3.99)],
        "Use half as much", "A different flower, but the same perfumed lift that makes biryani smell festive."),
      s("Extra fresh mint", "extra torn mint leaves", 54, M, [b("Fresh mint", "Produce", 2.49)],
        "Scatter 10 extra mint leaves between layers", "Adds freshness when floral waters aren't available."),
    ]),
  ing("shahi-jeera", "Shahi jeera (black cumin)", "shahi jeera",
    ["shahi jeera", "shah jeera", "black cumin", "kala jeera"],
    ["Indian", "Pakistani", "Persian"], "Spice & Seasoning", [...INDIAN, ...MIDEAST], b("Shahi jeera", "Spices", 4.49), [
      s("Cumin seed + pinch of caraway", "cumin seeds with a pinch of caraway", 80, M,
        [b("Cumin seed", "Spices", 3.49), b("Caraway seed", "Spices", 3.29)],
        "¾ tsp cumin + ¼ tsp caraway per tsp", "Shahi jeera tastes like a sweeter, earthier cross between the two."),
    ]),
  ing("mace", "Mace (javitri)", "mace",
    ["mace", "javitri"],
    ["Indian", "Indonesian"], "Spice & Seasoning", [...INDIAN, ...NAT], b("Mace blades", "Spices", 6.99), [
      s("Ground nutmeg", "ground nutmeg", 86, M, [b("Ground nutmeg", "Spices", 4.29)],
        "Use ¾ the amount", "Mace is the lacy coating of nutmeg — the same warmth, slightly brighter."),
    ]),
  ing("birista", "Birista (crispy fried onions)", "birista",
    ["birista", "fried onions", "crispy onions", "crispy shallots", "fried shallots", "bawang goreng"],
    ["Indian", "Pakistani", "Indonesian"], "Pantry", [...INDIAN, ...ASIAN], b("Birista fried onions", "International", 4.99), [
      s("French's Crispy Fried Onions", "crispy fried onions", 88, M, [b("French's Crispy Fried Onions", "Canned Goods", 3.79)],
        "1:1", "The green-bean-casserole topping is a well-known biryani shortcut."),
    ]),
  ing("green-chili", "Indian green chilies", "green chilies",
    ["green chilies", "green chili", "green chillies", "hari mirch", "indian green chili", "finger chili"],
    ["Indian", "Pakistani", "Bangladeshi"], "Produce", [...INDIAN, ...ASIAN], b("Indian green chilies", "Produce", 1.99), [
      s("Serrano peppers", "serrano peppers", 90, M, [b("Serrano peppers", "Produce", 0.99)],
        "1:1", "Thin-skinned, grassy and hot — the closest US supermarket match."),
    ]),
  ing("toor-dal", "Toor dal (split pigeon peas)", "toor dal",
    ["toor dal", "toovar dal", "arhar dal", "tuvar dal", "split pigeon peas"],
    ["Indian"], "Grain & Flour", INDIAN, b("Toor dal", "International", 4.99), [
      s("Yellow split peas", "yellow split peas", 82, M, [b("Yellow split peas", "Rice & Grains", 1.79)],
        "1:1 — soak 1 hour or simmer 15 min longer", "The same earthy, creamy body once cooked down."),
    ]),
  ing("biryani-masala", "Biryani masala", "biryani masala",
    ["biryani masala", "biryani spice", "shan biryani", "biryani mix"],
    ["Indian", "Pakistani"], "Spice & Seasoning", INDIAN, b("Biryani masala (Shan / MDH)", "International", 2.99), [
      s("Garam masala + cinnamon + cloves", "garam masala with extra cinnamon and cloves", 80, M,
        [b("Garam masala", "Spices", 4.49), b("Whole cloves", "Spices", 4.29)],
        "1 tbsp garam masala + pinch cinnamon + 2 crushed cloves", "Biryani masala is essentially a warmer, sweeter garam masala."),
    ]),
  ing("kashmiri-chili", "Kashmiri chili powder", "Kashmiri chili powder",
    ["kashmiri chili", "kashmiri chilli", "kashmiri mirch", "kashmiri red chili powder", "deggi mirch"],
    ["Indian", "Pakistani"], "Spice & Seasoning", INDIAN, b("Kashmiri chili powder", "Spices", 3.99), [
      s("Sweet paprika + pinch of cayenne", "sweet paprika with a pinch of cayenne", 86, M,
        [b("Sweet paprika", "Spices", 2.99), b("Ground cayenne pepper", "Spices", 2.49)],
        "1 tsp paprika + ⅛ tsp cayenne per tsp", "Kashmiri chili is prized for vivid color with mild heat — exactly paprika's strength."),
    ]),
  ing("saffron", "Saffron", "saffron",
    ["saffron", "kesar", "zafran", "azafran"],
    ["Indian", "Persian", "Moroccan", "Spanish"], "Spice & Seasoning", ["mainstream", ...INDIAN, ...MIDEAST], b("Saffron threads", "Spices", 8.99), [
      s("Turmeric + paprika (color only)", "a pinch of turmeric and paprika", 42, M, [b("Ground turmeric", "Spices", 2.99)],
        "A pinch of each", "Gives the golden color but not the floral, honeyed flavor."),
    ]),

  /* ---------------- Middle East & North Africa ---------------- */
  ing("jameed", "Jameed (dried fermented yogurt)", "jameed",
    ["jameed", "jameed balls", "liquid jameed", "kashk"],
    ["Jordanian", "Palestinian"], "Dairy", MIDEAST, b("Jameed (liquid or balls)", "International", 8.99), [
      s("Greek yogurt + feta + cornstarch", "yogurt–feta 'jameed' (Greek yogurt, feta & cornstarch)", 76, M,
        [b("Plain whole-milk Greek yogurt (32 oz)", "Dairy", 5.99), b("Feta cheese", "Dairy", 3.99), b("Cornstarch", "Baking", 1.99)],
        "3 cups yogurt + ½ cup feta + 1 tbsp cornstarch, blended", "Feta supplies jameed's salty, funky tang; cornstarch keeps the yogurt from splitting when boiled."),
    ]),
  ing("shrak", "Shrak (markook) bread", "shrak bread",
    ["shrak", "shraak", "markook", "saj bread", "mountain bread"],
    ["Jordanian", "Palestinian", "Lebanese"], "Grain & Flour", MIDEAST, b("Shrak / markook bread", "Bakery", 4.99), [
      s("Lavash", "lavash", 86, M, [b("Lavash flatbread", "Bakery", 3.99)],
        "1:1", "Paper-thin and soft — nearly identical."),
    ]),
  ing("baharat", "Baharat (seven spice)", "baharat",
    ["baharat", "seven spice", "7 spice", "lebanese seven spice"],
    ["Jordanian", "Lebanese", "Palestinian", "Syrian", "Iraqi"], "Spice & Seasoning", [...MIDEAST, ...NAT], b("Baharat", "Spices", 5.49), [
      s("DIY baharat", "homemade baharat (allspice, cumin, cinnamon, pepper & nutmeg)", 85, M,
        [b("Ground allspice", "Spices", 3.49), b("Ground cumin", "Spices", 2.99), b("Ground cinnamon", "Spices", 2.99)],
        "1 tsp allspice + ½ tsp each cumin, cinnamon, pepper + ¼ tsp nutmeg", "An allspice-forward warm blend — exactly what baharat is."),
    ]),
  ing("dried-lime", "Dried limes (limoo amani)", "dried limes",
    ["dried lime", "dried limes", "limoo amani", "limoo omani", "loomi", "black lime"],
    ["Persian", "Iraqi", "Gulf Arab"], "Spice & Seasoning", MIDEAST, b("Dried limes", "International", 4.99), [
      s("Lime zest + juice", "lime zest and juice", 70, M, [b("Limes", "Produce", 1.99)],
        "Zest + juice of 1 lime per 2 dried limes, added in the last 20 min", "Recreates the sour brightness; dried limes add a funky, fermented note you won't fully match."),
    ]),
  ing("preserved-lemon", "Preserved lemons", "preserved lemon rind",
    ["preserved lemon", "preserved lemons", "lemon confit", "citron confit"],
    ["Moroccan", "Tunisian", "Algerian"], "Produce", [...MIDEAST, ...NAT], b("Preserved lemons (jar)", "International", 7.99), [
      s("Quick-preserved lemon", "quick-preserved lemon zest", 78, M, [b("Lemons", "Produce", 0.79)],
        "Simmer zest strips of 2 lemons with 1 tbsp salt + their juice for 10 min", "A 10-minute shortcut to the soft, salty, intensely lemony rind."),
    ]),
  ing("ras-el-hanout", "Ras el hanout", "ras el hanout",
    ["ras el hanout", "ras al hanout", "ras el hanut"],
    ["Moroccan", "Tunisian", "Algerian"], "Spice & Seasoning", [...MIDEAST, ...NAT], b("Ras el hanout", "Spices", 5.99), [
      s("DIY ras el hanout", "homemade ras el hanout (cumin, coriander, ginger, cinnamon, turmeric & paprika)", 82, M,
        [b("Ground cumin", "Spices", 2.99), b("Ground coriander", "Spices", 2.99), b("Ground ginger", "Spices", 3.29), b("Ground cinnamon", "Spices", 2.99)],
        "1 tsp each cumin, coriander, ginger, turmeric + ½ tsp each cinnamon, paprika, allspice", "'Head of the shop' — a warm house blend you can build from the spice aisle."),
    ]),
  ing("sumac", "Sumac", "sumac",
    ["sumac", "sumak", "summaq"],
    ["Lebanese", "Persian", "Turkish", "Palestinian"], "Spice & Seasoning", [...MIDEAST, ...NAT], b("Ground sumac", "Spices", 4.99), [
      s("Lemon zest + salt", "lemon zest with a pinch of salt", 70, M, [b("Lemons", "Produce", 0.79)],
        "1 tsp zest + pinch of salt per tsp", "Tangy and bright — sumac's main job."),
    ]),
  ing("pomegranate-molasses", "Pomegranate molasses", "pomegranate molasses",
    ["pomegranate molasses", "dibs rumman", "rob-e anar", "pomegranate syrup"],
    ["Persian", "Lebanese", "Syrian", "Turkish"], "Sauce & Paste", [...MIDEAST, ...NAT], b("Pomegranate molasses", "International", 5.99), [
      s("Balsamic reduction + lemon + honey", "balsamic vinegar reduced with lemon juice and honey", 74, M,
        [b("Balsamic vinegar", "Oils & Vinegars", 3.99), b("Lemons", "Produce", 0.79)],
        "Reduce ¼ cup balsamic + 1 tbsp lemon + 1 tsp honey by half", "Thick, tart and fruity like the real thing."),
    ]),
  ing("aleppo-pepper", "Aleppo pepper (pul biber)", "Aleppo pepper",
    ["aleppo pepper", "pul biber", "halaby pepper", "urfa biber", "maras pepper"],
    ["Syrian", "Turkish", "Armenian"], "Spice & Seasoning", [...MIDEAST, ...NAT], b("Aleppo pepper", "Spices", 6.99), [
      s("Sweet paprika + crushed red pepper", "sweet paprika with a pinch of crushed red pepper", 78, M,
        [b("Sweet paprika", "Spices", 2.99), b("Crushed red pepper flakes", "Spices", 2.49)],
        "4 parts paprika : 1 part flakes", "Fruity, moderate heat — close to Aleppo's mild warmth."),
    ]),
  ing("labneh", "Labneh", "labneh",
    ["labneh", "labne", "lebni", "strained yogurt cheese"],
    ["Lebanese", "Palestinian", "Jordanian", "Syrian"], "Dairy", [...MIDEAST, ...NAT], b("Labneh", "Dairy", 5.99), [
      s("Strained Greek yogurt", "Greek yogurt strained overnight with a pinch of salt", 90, M,
        [b("Plain whole-milk Greek yogurt (32 oz)", "Dairy", 5.99)],
        "Strain 2 cups yogurt + ½ tsp salt overnight in a towel", "Labneh is simply salted yogurt strained thick."),
    ]),
  ing("zaatar", "Za'atar", "za'atar",
    ["za'atar", "zaatar", "zatar", "zahtar"],
    ["Lebanese", "Palestinian", "Jordanian", "Syrian"], "Spice & Seasoning", [...MIDEAST, ...NAT], b("Za'atar blend", "Spices", 5.49), [
      s("Thyme + oregano + sesame + lemon zest", "homemade za'atar (thyme, oregano, sesame & lemon zest)", 74, M,
        [b("Dried thyme", "Spices", 2.99), b("Sesame seeds", "Spices", 3.49)],
        "1 tbsp thyme + 1 tsp oregano + 1 tbsp sesame + ½ tsp zest", "Herby, nutty and tangy — the za'atar trifecta."),
    ]),

  /* ---------------- Europe & the Caucasus ---------------- */
  ing("twarog", "Twaróg (farmer's cheese)", "twaróg",
    ["twarog", "twaróg", "farmer's cheese", "farmers cheese", "tvorog", "quark"],
    ["Polish", "Ukrainian", "Russian", "German"], "Dairy", [...EURO, ...NAT], b("Twaróg / farmer's cheese", "Dairy", 4.99), [
      s("Small-curd cottage cheese, pressed", "cottage cheese pressed dry", 84, M, [b("Small-curd cottage cheese (4%)", "Dairy", 3.49)],
        "Press 1¼ cups in a towel 30 min per cup", "The same fresh curd, just wetter — pressing makes it crumbly like twaróg."),
      s("Whole-milk ricotta, drained", "drained ricotta", 78, M, [b("Whole-milk ricotta", "Dairy", 4.29)],
        "Drain 1 hour", "Creamier and sweeter, still lovely in pierogi."),
    ]),
  ing("sulguni", "Sulguni & imeruli cheese", "sulguni cheese",
    ["sulguni", "suluguni", "imeruli", "georgian cheese"],
    ["Georgian"], "Dairy", EURO, b("Sulguni cheese", "Deli", 8.99), [
      s("Low-moisture mozzarella + feta", "low-moisture mozzarella mixed with feta", 85, M,
        [b("Low-moisture mozzarella", "Dairy", 3.99), b("Feta cheese", "Dairy", 3.99)],
        "2 parts mozzarella : 1 part feta", "The classic Georgian-diaspora hack: stretch from mozzarella, brine from feta."),
    ]),
  ing("smetana", "Smetana", "smetana",
    ["smetana", "smietana", "śmietana", "russian sour cream"],
    ["Polish", "Russian", "Ukrainian"], "Dairy", EURO, b("Smetana", "Dairy", 3.99), [
      s("Sour cream + splash of heavy cream", "sour cream loosened with a little heavy cream", 90, M,
        [b("Full-fat sour cream", "Dairy", 2.49), b("Heavy cream", "Dairy", 3.49)],
        "4 parts sour cream : 1 part cream", "Smetana is richer and less tangy than American sour cream — cream fixes that."),
    ]),
];
