/** Client-safe cuisine metadata. */
export const CUISINE_FLAGS: Record<string, string> = {
  Nigerian: "🇳🇬",
  Ghanaian: "🇬🇭",
  Senegalese: "🇸🇳",
  Cameroonian: "🇨🇲",
  Ethiopian: "🇪🇹",
  Eritrean: "🇪🇷",
  Somali: "🇸🇴",
  Kenyan: "🇰🇪",
  "South African": "🇿🇦",
  Moroccan: "🇲🇦",
  Egyptian: "🇪🇬",
  Jamaican: "🇯🇲",
  Trinidadian: "🇹🇹",
  Haitian: "🇭🇹",
  Cuban: "🇨🇺",
  "Puerto Rican": "🇵🇷",
  Dominican: "🇩🇴",
  Guyanese: "🇬🇾",
  Mexican: "🇲🇽",
  Salvadoran: "🇸🇻",
  Guatemalan: "🇬🇹",
  Honduran: "🇭🇳",
  Colombian: "🇨🇴",
  Venezuelan: "🇻🇪",
  Peruvian: "🇵🇪",
  Brazilian: "🇧🇷",
  Argentinian: "🇦🇷",
  Vietnamese: "🇻🇳",
  Thai: "🇹🇭",
  Filipino: "🇵🇭",
  Indonesian: "🇮🇩",
  Malaysian: "🇲🇾",
  Cambodian: "🇰🇭",
  Lao: "🇱🇦",
  Korean: "🇰🇷",
  Chinese: "🇨🇳",
  Taiwanese: "🇹🇼",
  Japanese: "🇯🇵",
  Indian: "🇮🇳",
  Pakistani: "🇵🇰",
  Bangladeshi: "🇧🇩",
  "Sri Lankan": "🇱🇰",
  Nepali: "🇳🇵",
  Afghan: "🇦🇫",
  Persian: "🇮🇷",
  Iraqi: "🇮🇶",
  Lebanese: "🇱🇧",
  Syrian: "🇸🇾",
  Jordanian: "🇯🇴",
  Palestinian: "🇵🇸",
  Turkish: "🇹🇷",
  Armenian: "🇦🇲",
  Georgian: "🇬🇪",
  Greek: "🇬🇷",
  Italian: "🇮🇹",
  Portuguese: "🇵🇹",
  Polish: "🇵🇱",
  Ukrainian: "🇺🇦",
  Russian: "🇷🇺",
  German: "🇩🇪",
  American: "🇺🇸",
  British: "🇬🇧",
  Irish: "🇮🇪",
  French: "🇫🇷",
  Spanish: "🇪🇸",
  Dutch: "🇳🇱",
  Swedish: "🇸🇪",
  Norwegian: "🇳🇴",
  Danish: "🇩🇰",
  Finnish: "🇫🇮",
  Swiss: "🇨🇭",
  Austrian: "🇦🇹",
  Belgian: "🇧🇪",
  Hungarian: "🇭🇺",
  Czech: "🇨🇿",
  Romanian: "🇷🇴",
  Bulgarian: "🇧🇬",
  Serbian: "🇷🇸",
  Bosnian: "🇧🇦",
  Croatian: "🇭🇷",
  Albanian: "🇦🇱",
  Lithuanian: "🇱🇹",
  Canadian: "🇨🇦",
  Tunisian: "🇹🇳",
  Algerian: "🇩🇿",
  Libyan: "🇱🇾",
  Sudanese: "🇸🇩",
  Tanzanian: "🇹🇿",
  Ugandan: "🇺🇬",
  Congolese: "🇨🇩",
  Ivorian: "🇨🇮",
  Liberian: "🇱🇷",
  "Sierra Leonean": "🇸🇱",
  Zimbabwean: "🇿🇼",
  Rwandan: "🇷🇼",
  Israeli: "🇮🇱",
  "Saudi Arabian": "🇸🇦",
  Yemeni: "🇾🇪",
  Emirati: "🇦🇪",
  Cypriot: "🇨🇾",
  Burmese: "🇲🇲",
  Singaporean: "🇸🇬",
  Mongolian: "🇲🇳",
  Nepalese: "🇳🇵",
  Uzbekistani: "🇺🇿",
  "South Korean": "🇰🇷",
  Laotian: "🇱🇦",
  Iranian: "🇮🇷",
  Chilean: "🇨🇱",
  Ecuadorean: "🇪🇨",
  Bolivian: "🇧🇴",
  Paraguayan: "🇵🇾",
  Uruguayan: "🇺🇾",
  "Costa Rican": "🇨🇷",
  Panamanian: "🇵🇦",
  Nicaraguan: "🇳🇮",
  Barbadian: "🇧🇧",
  Australian: "🇦🇺",
  "New Zealander": "🇳🇿",
  Hawaiian: "🌺",
};

export const CUISINE_OPTIONS = Object.keys(CUISINE_FLAGS).sort((a, b) => a.localeCompare(b));

export function flagForCuisine(cuisine?: string | null): string {
  if (!cuisine) return "🍲";
  const c = cuisine.toLowerCase();
  const hit = Object.entries(CUISINE_FLAGS).find(([name]) => c.includes(name.toLowerCase()));
  return hit ? hit[1] : "🍲";
}
